-- ==============================================================================
-- Consolidated Migration: supabase/apply_all_unmigrated_changes.sql
-- Description: Applies all recent unmigrated database features in one safe, idempotent script:
--   1. OTC (Over-The-Counter) drug classification, tables, and atomic dispensing RPC
--   2. Medicine ID linkage on prescription items
--   3. Clinical expiration safety guard on dispensing
--   4. Medicine returns & inventory restocking audit table and RPCs
--   5. Walk-in (non-app) patient support for queue tickets
--   6. Mobile patient dispense logs RPC
--   7. Safe operational data refresh RPC
-- ==============================================================================

BEGIN;

-- ─────────────────────────────────────────────────────────────────────────────
-- SECTION 1: OVER-THE-COUNTER (OTC) DRUG SYSTEM
-- ─────────────────────────────────────────────────────────────────────────────

-- 1.1 Add drug_classification column to medicines
ALTER TABLE public.medicines
  ADD COLUMN IF NOT EXISTS drug_classification text NOT NULL DEFAULT 'rx'
    CHECK (drug_classification IN ('rx', 'otc'));

CREATE INDEX IF NOT EXISTS idx_medicines_classification
  ON public.medicines (drug_classification);

-- 1.2 Mark common known over-the-counter medications as 'otc'
UPDATE public.medicines
SET drug_classification = 'otc'
WHERE LOWER(TRIM(name)) IN (
  'paracetamol', 'ibuprofen', 'cetirizine', 'ascorbic acid', 'vitamin c',
  'multivitamins', 'oral rehydration salts', 'ors', 'antacid',
  'aluminum hydroxide', 'magnesium hydroxide', 'loratadine',
  'salbutamol syrup', 'carbocisteine', 'mefenamic acid'
)
AND drug_classification = 'rx';

-- 1.3 Create OTC Dispenses Table
CREATE TABLE IF NOT EXISTS public.otc_dispenses (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  reference_no text NOT NULL UNIQUE,
  citizen_id bigint REFERENCES public.citizens(id) ON DELETE SET NULL,
  walkin_patient_name text NOT NULL DEFAULT 'Walk-in Patient',
  dispensed_by_staff_id bigint NOT NULL REFERENCES public.staff(id),
  dispensed_at timestamptz NOT NULL DEFAULT now(),
  notes text
);

CREATE INDEX IF NOT EXISTS idx_otc_dispenses_ref ON public.otc_dispenses (reference_no);
CREATE INDEX IF NOT EXISTS idx_otc_dispenses_date ON public.otc_dispenses (dispensed_at DESC);
CREATE INDEX IF NOT EXISTS idx_otc_dispenses_citizen ON public.otc_dispenses (citizen_id);
CREATE INDEX IF NOT EXISTS idx_otc_dispenses_staff ON public.otc_dispenses (dispensed_by_staff_id);

-- 1.4 Create OTC Dispense Items Table
CREATE TABLE IF NOT EXISTS public.otc_dispense_items (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  otc_dispense_id bigint NOT NULL REFERENCES public.otc_dispenses(id) ON DELETE CASCADE,
  medicine_id bigint NOT NULL REFERENCES public.medicines(id),
  quantity integer NOT NULL CHECK (quantity > 0),
  unit text,
  instructions text,
  returned_quantity integer NOT NULL DEFAULT 0 CHECK (returned_quantity >= 0)
);

CREATE INDEX IF NOT EXISTS idx_otc_dispense_items_dispense ON public.otc_dispense_items (otc_dispense_id);
CREATE INDEX IF NOT EXISTS idx_otc_dispense_items_med ON public.otc_dispense_items (medicine_id);

-- RLS for OTC Dispenses
ALTER TABLE public.otc_dispenses ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.otc_dispense_items ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS otc_dispenses_select_staff ON public.otc_dispenses;
CREATE POLICY otc_dispenses_select_staff
  ON public.otc_dispenses
  FOR SELECT
  USING (
    EXISTS (
      SELECT 1 FROM public.staff s
      WHERE s.auth_user_id = auth.uid() AND s.status = 'active'
    )
  );

DROP POLICY IF EXISTS otc_dispense_items_select_staff ON public.otc_dispense_items;
CREATE POLICY otc_dispense_items_select_staff
  ON public.otc_dispense_items
  FOR SELECT
  USING (
    EXISTS (
      SELECT 1 FROM public.staff s
      WHERE s.auth_user_id = auth.uid() AND s.status = 'active'
    )
  );


-- ─────────────────────────────────────────────────────────────────────────────
-- SECTION 2: SYSTEM HARDENING & RESILIENCE
-- ─────────────────────────────────────────────────────────────────────────────

-- 2.1 Medicine ID Linkage on Prescription Items
ALTER TABLE public.prescription_items
  ADD COLUMN IF NOT EXISTS medicine_id bigint REFERENCES public.medicines(id) ON DELETE SET NULL;

CREATE INDEX IF NOT EXISTS idx_prescription_items_medicine_id
  ON public.prescription_items (medicine_id);

-- Backfill medicine_id from medicines table
UPDATE public.prescription_items pi
SET medicine_id = m.id
FROM public.medicines m
WHERE pi.medicine_id IS NULL
  AND LOWER(TRIM(pi.medicine_name)) = LOWER(TRIM(m.name))
  AND m.archived_at IS NULL;

-- 2.2 Add Returned Quantity Tracking
ALTER TABLE public.prescription_items
  ADD COLUMN IF NOT EXISTS returned_quantity integer NOT NULL DEFAULT 0
    CHECK (returned_quantity >= 0);

ALTER TABLE public.otc_dispense_items
  ADD COLUMN IF NOT EXISTS returned_quantity integer NOT NULL DEFAULT 0
    CHECK (returned_quantity >= 0);

-- 2.3 Dispense Returns Audit Table
CREATE TABLE IF NOT EXISTS public.dispense_returns (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  return_type text NOT NULL CHECK (return_type IN ('prescription', 'otc')),
  prescription_item_id bigint REFERENCES public.prescription_items(id) ON DELETE SET NULL,
  otc_item_id bigint REFERENCES public.otc_dispense_items(id) ON DELETE SET NULL,
  medicine_id bigint NOT NULL REFERENCES public.medicines(id),
  quantity integer NOT NULL CHECK (quantity > 0),
  reason text NOT NULL,
  returned_by_staff_id bigint NOT NULL REFERENCES public.staff(id),
  returned_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_dispense_returns_med ON public.dispense_returns(medicine_id);
CREATE INDEX IF NOT EXISTS idx_dispense_returns_staff ON public.dispense_returns(returned_by_staff_id);
CREATE INDEX IF NOT EXISTS idx_dispense_returns_rx_item ON public.dispense_returns(prescription_item_id);

ALTER TABLE public.dispense_returns ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS dispense_returns_select_staff ON public.dispense_returns;
CREATE POLICY dispense_returns_select_staff
  ON public.dispense_returns
  FOR SELECT
  USING (
    EXISTS (
      SELECT 1 FROM public.staff s
      WHERE s.auth_user_id = auth.uid() AND s.status = 'active'
    )
  );

-- 2.4 Non-App Walk-In Patient Support on Queue Tickets
ALTER TABLE public.queue_tickets
  ADD COLUMN IF NOT EXISTS walkin_patient_name text;

ALTER TABLE public.queue_tickets
  ALTER COLUMN citizen_id DROP NOT NULL;

COMMIT;


-- ─────────────────────────────────────────────────────────────────────────────
-- SECTION 3: RPC FUNCTIONS (ATOMIC PROCEDURES)
-- ─────────────────────────────────────────────────────────────────────────────

-- 3.1 Over-The-Counter Dispensing RPC
CREATE OR REPLACE FUNCTION public.dispense_otc_medicines(
  p_items jsonb,
  p_citizen_id bigint DEFAULT NULL,
  p_walkin_name text DEFAULT 'Walk-in Patient',
  p_notes text DEFAULT NULL
)
RETURNS json
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_staff_id bigint;
  v_staff_role text;
  v_otc_dispense_id bigint;
  v_reference_no text;
  v_seq integer;
  v_today_str text;
  v_item record;
  v_med record;
  v_total_items integer := 0;
BEGIN
  -- Authenticate staff caller
  SELECT s.id, s.role INTO v_staff_id, v_staff_role
  FROM public.staff s
  WHERE s.auth_user_id = auth.uid() AND s.status = 'active'
  LIMIT 1;

  IF v_staff_id IS NULL THEN
    RETURN json_build_object('error', 'Not authorized as active staff.');
  END IF;

  IF jsonb_array_length(p_items) = 0 THEN
    RETURN json_build_object('error', 'No medicines provided for OTC dispensing.');
  END IF;

  -- Generate unique reference: OTC-YYYYMMDD-XXXX
  v_today_str := to_char(timezone('Asia/Manila'::text, now()), 'YYYYMMDD');
  SELECT coalesce(count(*), 0) + 1 INTO v_seq
  FROM public.otc_dispenses
  WHERE reference_no LIKE 'OTC-' || v_today_str || '-%';

  v_reference_no := 'OTC-' || v_today_str || '-' || lpad(v_seq::text, 4, '0');

  -- Create OTC dispense header
  INSERT INTO public.otc_dispenses (
    reference_no, citizen_id, walkin_patient_name, dispensed_by_staff_id, notes
  ) VALUES (
    v_reference_no, p_citizen_id, coalesce(trim(p_walkin_name), 'Walk-in Patient'), v_staff_id, p_notes
  ) RETURNING id INTO v_otc_dispense_id;

  -- Process line items
  FOR v_item IN
    SELECT
      (item->>'medicine_id')::bigint AS medicine_id,
      (item->>'quantity')::integer AS quantity,
      item->>'unit' AS unit,
      item->>'instructions' AS instructions
    FROM jsonb_array_elements(p_items) AS item
  LOOP
    IF v_item.quantity <= 0 THEN
      CONTINUE;
    END IF;

    -- Lock and verify medicine stock
    SELECT * INTO v_med
    FROM public.medicines
    WHERE id = v_item.medicine_id
    FOR UPDATE;

    IF v_med.id IS NULL THEN
      RAISE EXCEPTION 'Medicine ID % not found.', v_item.medicine_id;
    END IF;

    IF v_med.drug_classification <> 'otc' THEN
      RAISE EXCEPTION 'Medicine "%" is classified as Rx and requires a prescription.', v_med.name;
    END IF;

    IF v_med.expiry_date IS NOT NULL AND v_med.expiry_date < CURRENT_DATE THEN
      RAISE EXCEPTION 'Medicine "%" has expired on %.', v_med.name, v_med.expiry_date;
    END IF;

    IF v_med.qty < v_item.quantity THEN
      RAISE EXCEPTION 'Insufficient stock for "%". Requested: %, Available: %',
        v_med.name, v_item.quantity, v_med.qty;
    END IF;

    -- Deduct inventory
    UPDATE public.medicines
    SET qty = qty - v_item.quantity
    WHERE id = v_med.id;

    -- Insert dispense item
    INSERT INTO public.otc_dispense_items (
      otc_dispense_id, medicine_id, quantity, unit, instructions
    ) VALUES (
      v_otc_dispense_id, v_med.id, v_item.quantity, coalesce(v_item.unit, v_med.unit), v_item.instructions
    );

    v_total_items := v_total_items + 1;
  END LOOP;

  IF v_total_items = 0 THEN
    RAISE EXCEPTION 'All line items had zero quantity.';
  END IF;

  RETURN json_build_object(
    'ok', true,
    'reference_no', v_reference_no,
    'otc_dispense_id', v_otc_dispense_id,
    'items_dispensed', v_total_items
  );
EXCEPTION WHEN others THEN
  RETURN json_build_object('error', SQLERRM);
END;
$$;

GRANT EXECUTE ON FUNCTION public.dispense_otc_medicines TO authenticated;


-- 3.2 Return Dispensed Prescription Item RPC
CREATE OR REPLACE FUNCTION public.return_dispensed_prescription_item(
  p_prescription_item_id bigint,
  p_quantity integer,
  p_reason text
)
RETURNS json
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_staff_id bigint;
  v_item record;
  v_header record;
  v_med record;
  v_all_remaining integer;
  v_all_dispensed integer;
  v_new_status text;
BEGIN
  -- Authenticate staff
  SELECT s.id INTO v_staff_id
  FROM public.staff s
  WHERE s.auth_user_id = auth.uid() AND s.status = 'active'
  LIMIT 1;

  IF v_staff_id IS NULL THEN
    RETURN json_build_object('error', 'Not authorized as active staff.');
  END IF;

  IF p_quantity <= 0 THEN
    RETURN json_build_object('error', 'Return quantity must be greater than zero.');
  END IF;

  -- Lock and retrieve prescription item
  SELECT * INTO v_item
  FROM public.prescription_items
  WHERE id = p_prescription_item_id
  FOR UPDATE;

  IF v_item.id IS NULL THEN
    RETURN json_build_object('error', 'Prescription item not found.');
  END IF;

  IF coalesce(v_item.dispensed_quantity, 0) < p_quantity THEN
    RETURN json_build_object('error', format('Cannot return more than dispensed quantity (%s).', coalesce(v_item.dispensed_quantity, 0)));
  END IF;

  -- Lock header
  SELECT * INTO v_header
  FROM public.prescription_headers
  WHERE id = v_item.prescription_id
  FOR UPDATE;

  -- Find medicine to restock
  IF v_item.medicine_id IS NOT NULL THEN
    SELECT * INTO v_med FROM public.medicines WHERE id = v_item.medicine_id FOR UPDATE;
  ELSE
    SELECT * INTO v_med FROM public.medicines
    WHERE lower(trim(name)) = lower(trim(v_item.medicine_name)) AND archived_at IS NULL
    LIMIT 1 FOR UPDATE;
  END IF;

  -- Restock medicine
  IF v_med.id IS NOT NULL THEN
    UPDATE public.medicines
    SET qty = qty + p_quantity
    WHERE id = v_med.id;
  END IF;

  -- Update prescription item quantities
  UPDATE public.prescription_items
  SET
    dispensed_quantity = dispensed_quantity - p_quantity,
    remaining_quantity = remaining_quantity + p_quantity,
    returned_quantity = coalesce(returned_quantity, 0) + p_quantity
  WHERE id = v_item.id;

  -- Recalculate header status
  SELECT
    coalesce(sum(remaining_quantity), 0),
    coalesce(sum(dispensed_quantity), 0)
  INTO v_all_remaining, v_all_dispensed
  FROM public.prescription_items
  WHERE prescription_id = v_header.id;

  IF v_all_dispensed = 0 THEN
    v_new_status := 'pending';
  ELSIF v_all_remaining > 0 THEN
    v_new_status := 'partial';
  ELSE
    v_new_status := 'dispensed';
  END IF;

  UPDATE public.prescription_headers
  SET dispensing_status = v_new_status
  WHERE id = v_header.id;

  -- Log in return audit table
  INSERT INTO public.dispense_returns (
    return_type, prescription_item_id, medicine_id, quantity, reason, returned_by_staff_id
  ) VALUES (
    'prescription', v_item.id, coalesce(v_med.id, v_item.medicine_id), p_quantity, coalesce(trim(p_reason), 'No reason specified'), v_staff_id
  );

  RETURN json_build_object(
    'ok', true,
    'message', format('Restocked %s units of %s. Prescription status is now %s.', p_quantity, v_item.medicine_name, v_new_status),
    'new_status', v_new_status
  );
EXCEPTION WHEN others THEN
  RETURN json_build_object('error', SQLERRM);
END;
$$;

GRANT EXECUTE ON FUNCTION public.return_dispensed_prescription_item TO authenticated;


-- 3.3 Return OTC Dispensed Item RPC
CREATE OR REPLACE FUNCTION public.return_otc_dispensed_item(
  p_otc_item_id bigint,
  p_quantity integer,
  p_reason text
)
RETURNS json
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_staff_id bigint;
  v_item record;
  v_med record;
BEGIN
  SELECT s.id INTO v_staff_id
  FROM public.staff s
  WHERE s.auth_user_id = auth.uid() AND s.status = 'active'
  LIMIT 1;

  IF v_staff_id IS NULL THEN
    RETURN json_build_object('error', 'Not authorized as active staff.');
  END IF;

  IF p_quantity <= 0 THEN
    RETURN json_build_object('error', 'Return quantity must be greater than zero.');
  END IF;

  SELECT * INTO v_item
  FROM public.otc_dispense_items
  WHERE id = p_otc_item_id
  FOR UPDATE;

  IF v_item.id IS NULL THEN
    RETURN json_build_object('error', 'OTC dispense item not found.');
  END IF;

  IF (v_item.quantity - coalesce(v_item.returned_quantity, 0)) < p_quantity THEN
    RETURN json_build_object('error', 'Cannot return more than net dispensed quantity.');
  END IF;

  SELECT * INTO v_med
  FROM public.medicines
  WHERE id = v_item.medicine_id
  FOR UPDATE;

  -- Restock medicine
  UPDATE public.medicines
  SET qty = qty + p_quantity
  WHERE id = v_med.id;

  -- Update returned quantity on item
  UPDATE public.otc_dispense_items
  SET returned_quantity = coalesce(returned_quantity, 0) + p_quantity
  WHERE id = v_item.id;

  -- Log return audit
  INSERT INTO public.dispense_returns (
    return_type, otc_item_id, medicine_id, quantity, reason, returned_by_staff_id
  ) VALUES (
    'otc', v_item.id, v_med.id, p_quantity, coalesce(trim(p_reason), 'No reason specified'), v_staff_id
  );

  RETURN json_build_object(
    'ok', true,
    'message', format('Restocked %s units of %s back into inventory.', p_quantity, v_med.name)
  );
EXCEPTION WHEN others THEN
  RETURN json_build_object('error', SQLERRM);
END;
$$;

GRANT EXECUTE ON FUNCTION public.return_otc_dispensed_item TO authenticated;


-- 3.4 Patient Dispense Logs RPC for Citizen App
DROP FUNCTION IF EXISTS public.get_my_prescription_dispense_logs();
DROP FUNCTION IF EXISTS public.get_my_prescription_dispense_logs(bigint, integer);
DROP FUNCTION IF EXISTS public.get_my_prescription_dispense_logs(integer, bigint);

CREATE OR REPLACE FUNCTION public.get_my_prescription_dispense_logs(
  p_limit integer DEFAULT 50,
  p_prescription_id bigint DEFAULT NULL
)
RETURNS TABLE (
  dispense_id           bigint,
  prescription_id       bigint,
  prescription_code     text,
  prescription_item_id  bigint,
  medicine_name         text,
  dosage                text,
  dispensed_quantity    integer,
  unit                  text,
  note                  text,
  pharmacist_name       text,
  dispensed_at          timestamptz
)
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_citizen record;
  v_limit integer := greatest(1, least(coalesce(p_limit, 50), 100));
BEGIN
  -- 1. Resolve citizen by auth_user_id or authenticated email
  SELECT * INTO v_citizen
  FROM public.citizens c
  WHERE c.auth_user_id = auth.uid()
     OR (c.email IS NOT NULL AND c.email = (SELECT email FROM auth.users WHERE id = auth.uid()))
  ORDER BY (CASE WHEN c.auth_user_id = auth.uid() THEN 0 ELSE 1 END) ASC
  LIMIT 1;

  IF v_citizen.id IS NULL THEN
    RETURN;
  END IF;

  -- Ensure citizen auth_user_id is linked
  IF v_citizen.auth_user_id IS NULL AND auth.uid() IS NOT NULL THEN
    UPDATE public.citizens SET auth_user_id = auth.uid() WHERE id = v_citizen.id;
  END IF;

  RETURN QUERY
  SELECT
    pid.id AS dispense_id,
    ph.id AS prescription_id,
    ph.prescription_code,
    pi.id AS prescription_item_id,
    coalesce(m.name, pi.medicine_name) AS medicine_name,
    coalesce(pi.dosage, '') AS dosage,
    pid.dispensed_quantity,
    coalesce(pid.unit, pi.unit, '') AS unit,
    coalesce(pid.note, '') AS note,
    coalesce(
      nullif(trim(concat_ws(' ', s.first_name, s.last_name)), ''),
      'Pharmacist'
    ) AS pharmacist_name,
    pid.dispensed_at
  FROM public.prescription_item_dispenses pid
  JOIN public.prescription_headers ph ON ph.id = pid.prescription_id
  JOIN public.prescription_items pi ON pi.id = pid.prescription_item_id
  LEFT JOIN public.medicines m ON m.id = pid.medicine_id
  LEFT JOIN public.staff s ON s.id = pid.dispensed_by_staff_id
  LEFT JOIN public.consultations con ON con.id = ph.consultation_id
  WHERE (
    -- Direct consultation patient link
    con.patient_citizen_id = v_citizen.id

    -- Direct patient identifier link
    OR ph.patient_identifier = v_citizen.id::text
    OR ph.patient_identifier ILIKE ('CIT-' || v_citizen.id::text)
    OR (
      ph.patient_identifier ~ '^\D*\d+\D*$' 
      AND regexp_replace(ph.patient_identifier, '\D', '', 'g') = v_citizen.id::text
    )

    -- Queue Ticket reference (e.g. Q-20260902-MC-001 or QUEUE-...)
    OR EXISTS (
      SELECT 1 FROM public.queue_tickets qt
      WHERE qt.citizen_id = v_citizen.id
        AND (
          qt.ticket_code = ph.patient_identifier
          OR ('QUEUE-' || qt.id::text) = ph.patient_identifier
          OR qt.id::text = ph.patient_identifier
        )
    )

    -- Consultation patient_identifier reference
    OR (con.patient_identifier IS NOT NULL AND (
      con.patient_identifier = v_citizen.id::text
      OR con.patient_identifier ILIKE ('CIT-' || v_citizen.id::text)
      OR (v_citizen.firstname IS NOT NULL AND length(trim(v_citizen.firstname)) > 1 AND con.patient_identifier ILIKE ('%' || trim(v_citizen.firstname) || '%'))
      OR (v_citizen.surname IS NOT NULL AND length(trim(v_citizen.surname)) > 1 AND con.patient_identifier ILIKE ('%' || trim(v_citizen.surname) || '%'))
    ))

    -- Name-based reference
    OR (
      v_citizen.firstname IS NOT NULL 
      AND length(trim(v_citizen.firstname)) > 1 
      AND ph.patient_identifier ILIKE ('%' || trim(v_citizen.firstname) || '%')
    )
    OR (
      v_citizen.surname IS NOT NULL 
      AND length(trim(v_citizen.surname)) > 1 
      AND ph.patient_identifier ILIKE ('%' || trim(v_citizen.surname) || '%')
    )

    -- Email reference
    OR (
      v_citizen.email IS NOT NULL 
      AND length(trim(v_citizen.email)) > 3 
      AND ph.patient_identifier ILIKE ('%' || trim(v_citizen.email) || '%')
    )
  )
  AND (p_prescription_id IS NULL OR ph.id = p_prescription_id)
  ORDER BY pid.dispensed_at DESC
  LIMIT v_limit;
END;
$$;

CREATE OR REPLACE FUNCTION public.get_my_prescription_dispense_logs()
RETURNS TABLE (
  dispense_id           bigint,
  prescription_id       bigint,
  prescription_code     text,
  prescription_item_id  bigint,
  medicine_name         text,
  dosage                text,
  dispensed_quantity    integer,
  unit                  text,
  note                  text,
  pharmacist_name       text,
  dispensed_at          timestamptz
)
LANGUAGE sql
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT * FROM public.get_my_prescription_dispense_logs(50, NULL);
$$;

GRANT EXECUTE ON FUNCTION public.get_my_prescription_dispense_logs(integer, bigint) TO authenticated;
GRANT EXECUTE ON FUNCTION public.get_my_prescription_dispense_logs() TO authenticated;

-- Diagnostic helper
CREATE OR REPLACE FUNCTION public.get_dispense_debug_summary()
RETURNS json
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_dispense_count integer;
  v_header_count integer;
  v_item_count integer;
  v_recent_dispenses json;
  v_recent_headers json;
BEGIN
  SELECT count(*) INTO v_dispense_count FROM public.prescription_item_dispenses;
  SELECT count(*) INTO v_header_count FROM public.prescription_headers;
  SELECT count(*) INTO v_item_count FROM public.prescription_items;

  SELECT coalesce(json_agg(row_to_json(d)), '[]'::json) INTO v_recent_dispenses
  FROM (
    SELECT id, prescription_id, prescription_item_id, dispensed_quantity, dispensed_at
    FROM public.prescription_item_dispenses
    ORDER BY id DESC LIMIT 5
  ) d;

  SELECT coalesce(json_agg(row_to_json(h)), '[]'::json) INTO v_recent_headers
  FROM (
    SELECT id, prescription_code, patient_identifier, consultation_id, dispensing_status, issued_at
    FROM public.prescription_headers
    ORDER BY id DESC LIMIT 5
  ) h;

  RETURN json_build_object(
    'total_dispenses', v_dispense_count,
    'total_headers', v_header_count,
    'total_items', v_item_count,
    'recent_dispenses', v_recent_dispenses,
    'recent_headers', v_recent_headers
  );
END;
$$;

GRANT EXECUTE ON FUNCTION public.get_dispense_debug_summary() TO anon, authenticated;


