name: ukonekmobile
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter

  # Utility packages
  flutter_native_splash: ^2.4.7
  qr_flutter: ^4.1.0
  flutter_multi_formatter: ^2.12.0
  image_picker: ^1.2.1
  string_similarity: ^2.1.1
  supabase_flutter: ^2.8.0
  app_links: ^7.0.0
  cupertino_icons: ^1.0.8
  intl: ^0.20.2
  flutter_local_notifications: ^21.0.0
  timezone: ^0.11.0
  shared_preferences: ^2.5.5
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.4
  flutter_lints: ^6.0.0

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/launcher icon/U-KOnekLogo.png"

flutter_native_splash:
  color: "#ffffff"
  image: "assets/logo/splash_logo.png"
  android_12:
    image: "assets/logo/splash_logo.png"
    icon_background_color: "#ffffff"
    color: "#ffffff"
  web: false

flutter:
  uses-material-design: true

  assets:
    - assets/welcome_screen/welcomPhoto-removebg-preview.png
    - assets/launcher icon/U-KOnekLogo.png
    - assets/logo/splash_logo.png
    - assets/logo/uKonekLogo.png