-- =============================================================================
-- Performance Optimization Migration Templates
-- Copy and customize these templates for your specific optimization needs
-- =============================================================================

-- TEMPLATE 1: ADD MISSING INDEXES
-- Use when analysis shows high sequential scan rates
-- =============================================================================

-- Foreign Key Indexes (Critical for join performance)
CREATE INDEX IF NOT EXISTS idx_table_name_foreign_key_column 
ON public.table_name(foreign_key_column);

-- Frequently Queried Columns
CREATE INDEX IF NOT EXISTS idx_table_name_status_date 
ON public.table_name(status, created_at DESC);

-- RLS Policy Support Indexes (Critical for Row-Level Security)
CREATE INDEX IF NOT EXISTS idx_table_name_user_id 
ON public.table_name(user_id) 
WHERE user_id IS NOT NULL;

-- Text Search Indexes
CREATE INDEX IF NOT EXISTS idx_table_name_search_text 
ON public.table_name USING GIN(to_tsvector('english', search_column));

-- Partial Indexes for Status Filtering
CREATE INDEX IF NOT EXISTS idx_table_name_active_status 
ON public.table_name(created_at DESC) 
WHERE status = 'active';

-- =============================================================================
-- TEMPLATE 2: REMOVE UNUSED INDEXES
-- Use when analysis shows indexes with zero usage
-- =============================================================================

-- Check usage before dropping:
-- SELECT indexname, idx_scan FROM pg_stat_user_indexes 
-- WHERE schemaname = 'public' AND idx_scan = 0;

-- DROP INDEX IF EXISTS unused_index_name;

-- =============================================================================
-- TEMPLATE 3: OPTIMIZE RLS POLICIES
-- Use when RLS policies cause performance issues
-- =============================================================================

-- Example: Optimize policy with proper index support
DROP POLICY IF EXISTS old_policy_name ON table_name;

CREATE POLICY optimized_policy_name ON table_name
    FOR ALL TO authenticated
    USING (
        -- Ensure this condition can use an index
        user_id = auth.uid()
        -- Add composite conditions carefully
        AND status IN ('active', 'pending')
    );

-- Add supporting index for the policy
CREATE INDEX IF NOT EXISTS idx_table_name_rls_optimized 
ON public.table_name(user_id, status) 
WHERE user_id IS NOT NULL;

-- =============================================================================
-- TEMPLATE 4: TABLE PARTITIONING (for large time-series data)
-- Use for tables with millions of rows organized by date
-- =============================================================================

-- Step 1: Create partitioned table
CREATE TABLE public.large_table_partitioned (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    created_at timestamptz NOT NULL DEFAULT now(),
    -- other columns...
    PRIMARY KEY (id, created_at)
) PARTITION BY RANGE (created_at);

-- Step 2: Create monthly partitions
CREATE TABLE public.large_table_y2026m08 PARTITION OF public.large_table_partitioned
    FOR VALUES FROM ('2026-08-01') TO ('2026-09-01');

CREATE TABLE public.large_table_y2026m09 PARTITION OF public.large_table_partitioned
    FOR VALUES FROM ('2026-09-01') TO ('2026-10-01');

-- Step 3: Create function to automatically create partitions
CREATE OR REPLACE FUNCTION create_monthly_partition(table_name text, start_date date)
RETURNS void AS $$
DECLARE
    partition_name text;
    end_date date;
BEGIN
    end_date := start_date + interval '1 month';
    partition_name := table_name || '_y' || 
                     extract(year from start_date) || 'm' || 
                     lpad(extract(month from start_date)::text, 2, '0');
    
    EXECUTE format('CREATE TABLE IF NOT EXISTS %I PARTITION OF %I 
                    FOR VALUES FROM (%L) TO (%L)',
                   partition_name, table_name, start_date, end_date);
END;
$$ LANGUAGE plpgsql;

-- =============================================================================
-- TEMPLATE 5: QUERY OPTIMIZATION
-- Common query patterns and their optimizations
-- =============================================================================

-- Example: Optimize pagination queries
-- BEFORE (slow for large offsets):
-- SELECT * FROM table_name ORDER BY created_at DESC OFFSET 10000 LIMIT 50;

-- AFTER (cursor-based pagination):
-- SELECT * FROM table_name 
-- WHERE created_at < '2026-08-14 10:00:00'
-- ORDER BY created_at DESC LIMIT 50;

-- Supporting index:
CREATE INDEX IF NOT EXISTS idx_table_name_created_at_desc 
ON public.table_name(created_at DESC);

-- =============================================================================
-- TEMPLATE 6: MATERIALIZED VIEWS FOR COMPLEX AGGREGATIONS
-- Use for frequently accessed aggregated data
-- =============================================================================

-- Create materialized view for dashboard metrics
CREATE MATERIALIZED VIEW IF NOT EXISTS public.dashboard_metrics AS
SELECT 
    date_trunc('day', created_at) as date,
    count(*) as total_records,
    count(*) FILTER (WHERE status = 'completed') as completed_count,
    avg(processing_time) as avg_processing_time
FROM public.transactions
WHERE created_at >= CURRENT_DATE - INTERVAL '30 days'
GROUP BY date_trunc('day', created_at)
ORDER BY date DESC;

-- Create index on materialized view
CREATE INDEX IF NOT EXISTS idx_dashboard_metrics_date 
ON public.dashboard_metrics(date DESC);

-- Create function to refresh materialized view
CREATE OR REPLACE FUNCTION refresh_dashboard_metrics()
RETURNS void AS $$
BEGIN
    REFRESH MATERIALIZED VIEW CONCURRENTLY public.dashboard_metrics;
END;
$$ LANGUAGE plpgsql;

-- =============================================================================
-- TEMPLATE 7: CONNECTION POOLING OPTIMIZATION
-- Configure optimal connection settings
-- =============================================================================

-- These are typically set at database level, not in migrations
-- Document recommended settings:

/*
Recommended Supabase connection settings:

1. In Supabase Dashboard > Settings > Database:
   - Connection pooling: Enabled
   - Pool size: 15-25 (adjust based on load)
   - Max client connections: 200

2. In your application:
   - Use connection pooling (PgBouncer is built into Supabase)
   - Set appropriate timeouts
   - Implement proper error handling

3. Monitor connection usage:
   - Check active connections regularly
   - Set up alerts for high connection usage
*/

-- =============================================================================
-- TEMPLATE 8: VACUUM AND MAINTENANCE
-- Regular maintenance tasks for optimal performance
-- =============================================================================

-- Note: These are typically run outside of migrations
-- Create monitoring function to check maintenance needs

CREATE OR REPLACE FUNCTION check_maintenance_needs()
RETURNS TABLE(
    table_name text,
    dead_tuples bigint,
    live_tuples bigint,
    bloat_percent numeric,
    last_vacuum timestamptz,
    recommendation text
) AS $$
BEGIN
    RETURN QUERY
    SELECT 
        schemaname || '.' || tablename as table_name,
        n_dead_tup,
        n_live_tup,
        CASE 
            WHEN n_live_tup > 0 THEN 
                round((n_dead_tup::numeric / n_live_tup::numeric) * 100, 2)
            ELSE 0
        END as bloat_percent,
        last_vacuum,
        CASE 
            WHEN n_dead_tup > n_live_tup * 0.2 THEN 'URGENT: Manual VACUUM needed'
            WHEN n_dead_tup > n_live_tup * 0.1 THEN 'Consider VACUUM'
            ELSE 'Healthy'
        END as recommendation
    FROM pg_stat_user_tables 
    ORDER BY bloat_percent DESC;
END;
$$ LANGUAGE plpgsql;

-- =============================================================================
-- TEMPLATE 9: MONITORING AND ALERTING SETUP
-- Set up performance monitoring
-- =============================================================================

-- Create performance monitoring table
CREATE TABLE IF NOT EXISTS public.performance_logs (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    metric_name text NOT NULL,
    metric_value numeric,
    recorded_at timestamptz NOT NULL DEFAULT now(),
    metadata jsonb
);

-- Create function to log performance metrics
CREATE OR REPLACE FUNCTION log_performance_metric(
    p_metric_name text,
    p_metric_value numeric,
    p_metadata jsonb DEFAULT NULL
)
RETURNS void AS $$
BEGIN
    INSERT INTO public.performance_logs (metric_name, metric_value, metadata)
    VALUES (p_metric_name, p_metric_value, p_metadata);
END;
$$ LANGUAGE plpgsql;

-- Create indexes for performance logs
CREATE INDEX IF NOT EXISTS idx_performance_logs_metric_time 
ON public.performance_logs(metric_name, recorded_at DESC);

-- =============================================================================
-- USAGE INSTRUCTIONS
-- =============================================================================

/*
1. Copy the relevant template sections to a new migration file
2. Customize table names, column names, and conditions for your schema
3. Test the migration on a development database first
4. Apply to production during low-traffic periods
5. Monitor the impact using the performance monitoring tools
6. Document the changes and their expected performance improvements

Example workflow:
1. Run performance analysis queries
2. Identify specific issues (missing indexes, slow queries, etc.)
3. Choose appropriate template from above
4. Create new migration: supabase migration new optimize_performance_YYYYMMDD
5. Apply migration: supabase db push
6. Monitor results and iterate as needed
*/