-- Enhanced Medicine Inventory: expiry dates, supplier tracking,
-- generic/brand names, dosage form, reorder levels, categories,
-- restock logs, and alert RPCs.

-- ============================================================
-- 1. Enhance medicines table
-- ============================================================

alter table if exists public.medicines
  add column if not exists generic_name text,
  add column if not exists brand_name text,
  add column if not exists dosage_form text,
  add column if not exists dosage_strength text,
  add column if not exists expiration_date date,
  add column if not exists batch_number text,
  add column if not exists supplier_name text,
  add column if not exists supplier_contact text,
  add column if not exists reorder_level integer not null default 10,
  add column if not exists category text not null default 'general',
  add column if not exists last_restocked_at timestamptz;

-- Category constraint
alter table public.medicines
  drop constraint if exists medicines_category_valid;
alter table public.medicines
  add constraint medicines_category_valid
  check (category in ('general', 'fast_moving', 'slow_moving', 'critical', 'controlled'));

-- Dosage form constraint
alter table public.medicines
  drop constraint if exists medicines_dosage_form_valid;
alter table public.medicines
  add constraint medicines_dosage_form_valid
  check (dosage_form is null or dosage_form in (
    'tablet', 'capsule', 'syrup', 'suspension', 'injection',
    'cream', 'ointment', 'drops', 'inhaler', 'suppository',
    'patch', 'powder', 'solution', 'gel', 'spray', 'other'
  ));

-- Index for expiry alerts
create index if not exists idx_medicines_expiration_date
  on public.medicines(expiration_date)
  where expiration_date is not null and archived_at is null;

-- Index for low stock
create index if not exists idx_medicines_qty_reorder
  on public.medicines(qty, reorder_level)
  where archived_at is null;

-- ============================================================
-- 2. Medicine restock logs
-- ============================================================

create table if not exists public.medicine_restock_logs (
  id bigint generated by default as identity primary key,
  medicine_id bigint not null references public.medicines(id) on delete cascade,
  qty_added integer not null,
  previous_qty integer not null default 0,
  resulting_qty integer not null,
  supplier_name text,
  supplier_contact text,
  batch_number text,
  expiration_date date,
  unit_cost numeric(10,2),
  total_cost numeric(10,2),
  notes text,
  restocked_by_staff_id bigint references public.staff(id) on delete set null,
  created_at timestamptz not null default now(),
  constraint medicine_restock_logs_qty_positive check (qty_added > 0)
);

create index if not exists idx_medicine_restock_logs_medicine_id
  on public.medicine_restock_logs(medicine_id, created_at desc);

alter table public.medicine_restock_logs enable row level security;

drop policy if exists medicine_restock_logs_select_active_staff on public.medicine_restock_logs;
create policy medicine_restock_logs_select_active_staff
  on public.medicine_restock_logs
  for select
  using (
    public.is_admin()
    or exists (
      select 1 from public.staff s
      where s.auth_user_id = auth.uid()
        and lower(trim(coalesce(s.status, ''))) = 'active'
    )
  );

drop policy if exists medicine_restock_logs_insert_authorized on public.medicine_restock_logs;
create policy medicine_restock_logs_insert_authorized
  on public.medicine_restock_logs
  for insert
  with check (
    public.is_admin()
    or exists (
      select 1 from public.staff s
      where s.auth_user_id = auth.uid()
        and lower(trim(coalesce(s.status, ''))) = 'active'
        and lower(trim(coalesce(s.role, ''))) in ('doctor', 'nurse', 'pharmacist', 'staff')
    )
  );

grant select, insert on public.medicine_restock_logs to authenticated;

-- ============================================================
-- 3. RPC: Restock medicine (atomic qty update + log)
-- ============================================================

create or replace function public.restock_medicine(
  p_medicine_id bigint,
  p_qty_added integer,
  p_supplier_name text default null,
  p_supplier_contact text default null,
  p_batch_number text default null,
  p_expiration_date date default null,
  p_unit_cost numeric default null,
  p_notes text default null
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_staff_id bigint;
  v_medicine public.medicines%rowtype;
  v_new_qty integer;
begin
  -- Resolve staff
  select s.id into v_staff_id
  from public.staff s
  where s.auth_user_id = auth.uid()
    and lower(trim(coalesce(s.status, ''))) = 'active';

  if v_staff_id is null then
    return jsonb_build_object('ok', false, 'error', 'Unauthorized: active staff required.');
  end if;

  if coalesce(p_qty_added, 0) <= 0 then
    return jsonb_build_object('ok', false, 'error', 'Quantity must be greater than zero.');
  end if;

  -- Lock and fetch medicine
  select m.* into v_medicine
  from public.medicines m
  where m.id = p_medicine_id and m.archived_at is null
  for update;

  if v_medicine.id is null then
    return jsonb_build_object('ok', false, 'error', 'Medicine not found or archived.');
  end if;

  v_new_qty := coalesce(v_medicine.qty, 0) + p_qty_added;

  -- Update medicine
  update public.medicines m
  set qty = v_new_qty,
      supplier_name = coalesce(nullif(trim(p_supplier_name), ''), m.supplier_name),
      supplier_contact = coalesce(nullif(trim(p_supplier_contact), ''), m.supplier_contact),
      batch_number = coalesce(nullif(trim(p_batch_number), ''), m.batch_number),
      expiration_date = coalesce(p_expiration_date, m.expiration_date),
      last_restocked_at = now()
  where m.id = p_medicine_id;

  -- Log the restock
  insert into public.medicine_restock_logs (
    medicine_id, qty_added, previous_qty, resulting_qty,
    supplier_name, supplier_contact, batch_number, expiration_date,
    unit_cost, total_cost, notes, restocked_by_staff_id
  ) values (
    p_medicine_id, p_qty_added, coalesce(v_medicine.qty, 0), v_new_qty,
    nullif(trim(coalesce(p_supplier_name, '')), ''),
    nullif(trim(coalesce(p_supplier_contact, '')), ''),
    nullif(trim(coalesce(p_batch_number, '')), ''),
    p_expiration_date,
    p_unit_cost,
    case when p_unit_cost is not null then p_unit_cost * p_qty_added else null end,
    nullif(trim(coalesce(p_notes, '')), ''),
    v_staff_id
  );

  -- Also log in inventory transactions
  insert into public.medicine_inventory_transactions (
    medicine_id, medicine_name, change_qty, resulting_qty,
    reason, doctor_staff_id
  ) values (
    p_medicine_id, v_medicine.name, p_qty_added, v_new_qty,
    'RESTOCK', v_staff_id
  );

  return jsonb_build_object('ok', true, 'new_qty', v_new_qty);
end;
$$;

revoke all on function public.restock_medicine(bigint, integer, text, text, text, date, numeric, text) from public;
grant execute on function public.restock_medicine(bigint, integer, text, text, text, date, numeric, text) to authenticated;

-- ============================================================
-- 4. RPC: Get low stock medicines
-- ============================================================

create or replace function public.get_low_stock_medicines(
  p_threshold integer default null
)
returns table (
  id bigint,
  name text,
  generic_name text,
  brand_name text,
  qty integer,
  reorder_level integer,
  unit text,
  category text,
  expiration_date date
)
language sql
security definer
set search_path = public
as $$
  select
    m.id, m.name, coalesce(m.generic_name, ''), coalesce(m.brand_name, ''),
    m.qty, m.reorder_level, coalesce(m.unit, ''), m.category,
    m.expiration_date
  from public.medicines m
  where m.archived_at is null
    and m.qty <= coalesce(p_threshold, m.reorder_level)
  order by m.qty asc, m.name asc;
$$;

grant execute on function public.get_low_stock_medicines(integer) to authenticated;

-- ============================================================
-- 5. RPC: Get expiring medicines
-- ============================================================

create or replace function public.get_expiring_medicines(
  p_days_ahead integer default 90
)
returns table (
  id bigint,
  name text,
  generic_name text,
  brand_name text,
  qty integer,
  unit text,
  expiration_date date,
  days_until_expiry integer,
  supplier_name text
)
language sql
security definer
set search_path = public
as $$
  select
    m.id, m.name, coalesce(m.generic_name, ''), coalesce(m.brand_name, ''),
    m.qty, coalesce(m.unit, ''), m.expiration_date,
    (m.expiration_date - current_date)::integer as days_until_expiry,
    coalesce(m.supplier_name, '')
  from public.medicines m
  where m.archived_at is null
    and m.expiration_date is not null
    and m.expiration_date <= (current_date + coalesce(p_days_ahead, 90))
  order by m.expiration_date asc;
$$;

grant execute on function public.get_expiring_medicines(integer) to authenticated;
