-- Refactor citizen family model to explicit families + family_status.
--
-- Migration goals:
-- 1) Create normalized families table.
-- 2) Migrate existing citizens.family_number values to families rows.
-- 3) Enforce explicit citizen family state:
--    - family_id is null  => family_status = 'NO_FAMILY_YET'
--    - family_id is set   => family_status = 'HAS_FAMILY'
-- 4) Provide RPCs for web/backend list/filter/update flows.

create table if not exists public.families (
  id bigint generated by default as identity primary key,
  family_number varchar(100) not null unique,
  address text,
  created_at timestamptz not null default now(),
  constraint families_family_number_not_blank check (nullif(trim(family_number), '') is not null)
);

create index if not exists idx_families_family_number on public.families (family_number);

alter table public.families enable row level security;

drop policy if exists families_select_active_staff on public.families;
create policy families_select_active_staff
  on public.families
  for select
  using (
    exists (
      select 1
      from public.staff s
      where s.auth_user_id = auth.uid()
        and lower(trim(coalesce(s.status, ''))) = 'active'
    )
  );

grant select on public.families to authenticated;

do $$
begin
  if not exists (
    select 1
    from pg_type t
    join pg_namespace n on n.oid = t.typnamespace
    where n.nspname = 'public'
      and t.typname = 'family_status_enum'
  ) then
    create type public.family_status_enum as enum ('HAS_FAMILY', 'NO_FAMILY_YET');
  end if;
end;
$$;

alter table public.citizens
  add column if not exists family_id bigint,
  add column if not exists family_status public.family_status_enum;

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'citizens_family_id_fkey'
      and conrelid = 'public.citizens'::regclass
  ) then
    alter table public.citizens
      add constraint citizens_family_id_fkey
      foreign key (family_id)
      references public.families(id)
      on delete set null;
  end if;
end;
$$;

create or replace function public.normalize_family_number(p_value text)
returns text
language plpgsql
immutable
as $$
declare
  v_value text;
begin
  v_value := upper(trim(coalesce(p_value, '')));
  if v_value = '' then
    return null;
  end if;
  return v_value;
end;
$$;

create or replace function public.ensure_family(
  p_family_number text,
  p_address text default null
)
returns bigint
language plpgsql
security definer
set search_path = public
as $$
declare
  v_family_id bigint;
  v_family_number text;
  v_address text;
begin
  v_family_number := public.normalize_family_number(p_family_number);
  v_address := nullif(trim(coalesce(p_address, '')), '');

  if v_family_number is null then
    return null;
  end if;

  insert into public.families (family_number, address)
  values (v_family_number, v_address)
  on conflict (family_number)
  do update
    set address = coalesce(public.families.address, excluded.address)
  returning id into v_family_id;

  return v_family_id;
end;
$$;

-- Data migration notes:
-- - Existing non-empty citizens.family_number values are normalized and inserted into public.families.
-- - Citizens are then linked to family_id.
-- - Records without a family number are explicitly marked NO_FAMILY_YET.
do $$
begin
  if exists (
    select 1
    from information_schema.columns
    where table_schema = 'public'
      and table_name = 'citizens'
      and column_name = 'family_number'
  ) then
    insert into public.families (family_number)
    select distinct public.normalize_family_number(c.family_number)
    from public.citizens c
    where public.normalize_family_number(c.family_number) is not null
    on conflict (family_number) do nothing;

    update public.citizens c
    set family_id = f.id
    from public.families f
    where public.normalize_family_number(c.family_number) = f.family_number
      and c.family_id is null;
  end if;
end;
$$;

update public.citizens
set family_status = case
  when family_id is null then 'NO_FAMILY_YET'::public.family_status_enum
  else 'HAS_FAMILY'::public.family_status_enum
end;

alter table public.citizens
  alter column family_status set default 'NO_FAMILY_YET'::public.family_status_enum,
  alter column family_status set not null;

alter table public.citizens
  drop constraint if exists citizens_family_assignment_consistent;

alter table public.citizens
  add constraint citizens_family_assignment_consistent
  check (
    (family_id is null and family_status = 'NO_FAMILY_YET'::public.family_status_enum)
    or
    (family_id is not null and family_status = 'HAS_FAMILY'::public.family_status_enum)
  );

create index if not exists idx_citizens_family_id on public.citizens (family_id);
create index if not exists idx_citizens_family_status on public.citizens (family_status);

alter table public.citizens
  drop constraint if exists citizens_family_number_citizen_only;
drop index if exists public.idx_citizens_family_number;

alter table public.citizens
  drop column if exists family_number;

drop function if exists public.complete_my_citizen_profile(
  text,
  text,
  text,
  date,
  integer,
  text,
  text,
  text,
  text,
  text,
  text,
  text
);

drop function if exists public.complete_my_citizen_profile(
  text,
  text,
  text,
  date,
  integer,
  text,
  text,
  text,
  text,
  text,
  text,
  text,
  text
);

create or replace function public.complete_my_citizen_profile(
  p_firstname text,
  p_surname text,
  p_middle_initial text default null,
  p_date_of_birth date default null,
  p_age integer default null,
  p_contact_number text default null,
  p_sex text default null,
  p_complete_address text default null,
  p_emergency_contact_complete_name text default null,
  p_emergency_contact_contact_number text default null,
  p_relation text default null,
  p_family_number text default null,
  p_no_family_yet boolean default false,
  p_family_address text default null,
  p_username text default null
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_citizen_id bigint;
  v_username text;
  v_auth_email text;
  v_family_id bigint;
  v_no_family_yet boolean;
  v_family_number text;
begin
  select c.id
  into v_citizen_id
  from public.citizens c
  where c.auth_user_id = auth.uid()
  limit 1;

  if v_citizen_id is null then
    return jsonb_build_object('ok', false, 'error', 'Citizen profile not found for verified account.');
  end if;

  v_username := nullif(trim(coalesce(p_username, '')), '');
  if v_username is null then
    return jsonb_build_object('ok', false, 'error', 'Username is required.');
  end if;

  if exists (
    select 1
    from public.citizens c
    where lower(trim(coalesce(c.username, ''))) = lower(v_username)
      and c.id <> v_citizen_id
  ) then
    return jsonb_build_object('ok', false, 'error', 'Username already used, please choose another username.');
  end if;

  v_auth_email := lower(trim(coalesce(auth.jwt() ->> 'email', '')));
  v_no_family_yet := coalesce(p_no_family_yet, false);
  v_family_number := public.normalize_family_number(p_family_number);

  if v_no_family_yet and v_family_number is not null then
    return jsonb_build_object('ok', false, 'error', 'Choose either family number or "No Family Yet", not both.');
  end if;

  if v_no_family_yet then
    v_family_id := null;
  elsif v_family_number is not null then
    v_family_id := public.ensure_family(v_family_number, p_family_address);
  else
    select c.family_id into v_family_id
    from public.citizens c
    where c.id = v_citizen_id;
  end if;

  update public.citizens c
  set
    firstname = case
      when nullif(trim(coalesce(p_firstname, '')), '') is not null then trim(p_firstname)
      else c.firstname
    end,
    surname = case
      when nullif(trim(coalesce(p_surname, '')), '') is not null then trim(p_surname)
      else c.surname
    end,
    middle_initial = nullif(trim(coalesce(p_middle_initial, '')), ''),
    date_of_birth = coalesce(p_date_of_birth, c.date_of_birth),
    age = coalesce(p_age, c.age),
    contact_number = nullif(trim(coalesce(p_contact_number, '')), ''),
    sex = nullif(trim(coalesce(p_sex, '')), ''),
    complete_address = nullif(trim(coalesce(p_complete_address, '')), ''),
    emergency_contact_complete_name = nullif(trim(coalesce(p_emergency_contact_complete_name, '')), ''),
    emergency_contact_contact_number = nullif(trim(coalesce(p_emergency_contact_contact_number, '')), ''),
    relation = nullif(trim(coalesce(p_relation, '')), ''),
    family_id = v_family_id,
    family_status = case
      when v_family_id is null then 'NO_FAMILY_YET'::public.family_status_enum
      else 'HAS_FAMILY'::public.family_status_enum
    end,
    username = v_username,
    email = case
      when v_auth_email <> '' then v_auth_email
      else c.email
    end
  where c.id = v_citizen_id;

  return jsonb_build_object('ok', true);
end;
$$;

grant execute on function public.complete_my_citizen_profile(
  text,
  text,
  text,
  date,
  integer,
  text,
  text,
  text,
  text,
  text,
  text,
  text,
  boolean,
  text,
  text
) to authenticated;

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  v_role text;
  v_family_number text;
  v_no_family_yet boolean;
  v_family_id bigint;
begin
  v_role := lower(coalesce(new.raw_user_meta_data->>'role', ''));

  if lower(coalesce(new.email, '')) = 'admin@ukonek.local' then
    insert into public.staff (
      first_name,
      middle_name,
      last_name,
      birthday,
      gender,
      username,
      employee_id,
      email,
      role,
      consent_given,
      status,
      auth_user_id
    ) values (
      'System',
      '-',
      'Admin',
      date '1990-01-01',
      'Prefer not to say',
      'admin',
      '01',
      'admin@ukonek.local',
      'admin',
      true,
      'Active',
      new.id
    )
    on conflict (email)
    do update set
      role = excluded.role,
      status = excluded.status,
      auth_user_id = excluded.auth_user_id;

    return new;
  end if;

  if v_role = 'citizen' then
    v_family_number := public.normalize_family_number(new.raw_user_meta_data->>'family_number');
    v_no_family_yet := lower(trim(coalesce(new.raw_user_meta_data->>'no_family_yet', 'false'))) in ('1', 'true', 'yes', 'y');

    if v_no_family_yet then
      v_family_id := null;
    elsif v_family_number is not null then
      v_family_id := public.ensure_family(v_family_number, new.raw_user_meta_data->>'complete_address');
    else
      v_family_id := null;
      v_no_family_yet := true;
    end if;

    insert into public.citizens (
      firstname,
      surname,
      middle_initial,
      date_of_birth,
      age,
      contact_number,
      sex,
      email,
      complete_address,
      emergency_contact_complete_name,
      emergency_contact_contact_number,
      relation,
      family_id,
      family_status,
      username,
      role,
      auth_user_id
    ) values (
      coalesce(new.raw_user_meta_data->>'firstname', ''),
      coalesce(new.raw_user_meta_data->>'surname', ''),
      new.raw_user_meta_data->>'middle_initial',
      (new.raw_user_meta_data->>'date_of_birth')::date,
      (new.raw_user_meta_data->>'age')::integer,
      new.raw_user_meta_data->>'contact_number',
      new.raw_user_meta_data->>'sex',
      new.email,
      new.raw_user_meta_data->>'complete_address',
      new.raw_user_meta_data->>'emergency_contact_complete_name',
      new.raw_user_meta_data->>'emergency_contact_contact_number',
      new.raw_user_meta_data->>'relation',
      v_family_id,
      case
        when v_family_id is null then 'NO_FAMILY_YET'::public.family_status_enum
        else 'HAS_FAMILY'::public.family_status_enum
      end,
      new.raw_user_meta_data->>'username',
      'citizen',
      new.id
    )
    on conflict (email)
    do update set
      firstname = excluded.firstname,
      surname = excluded.surname,
      middle_initial = excluded.middle_initial,
      date_of_birth = excluded.date_of_birth,
      age = excluded.age,
      contact_number = excluded.contact_number,
      sex = excluded.sex,
      complete_address = excluded.complete_address,
      emergency_contact_complete_name = excluded.emergency_contact_complete_name,
      emergency_contact_contact_number = excluded.emergency_contact_contact_number,
      relation = excluded.relation,
      family_id = excluded.family_id,
      family_status = excluded.family_status,
      username = excluded.username,
      auth_user_id = excluded.auth_user_id;
  end if;

  return new;
end;
$$;

create or replace function public.api_get_citizens(
  p_name text default null,
  p_family_number text default null,
  p_family_status text default null
)
returns table (
  id bigint,
  username text,
  firstname text,
  surname text,
  email text,
  contact_number text,
  family_id bigint,
  family_number text,
  family_status text,
  created_at timestamptz
)
language sql
security definer
set search_path = public
as $$
  select
    c.id,
    c.username,
    c.firstname,
    c.surname,
    c.email,
    c.contact_number,
    c.family_id,
    f.family_number,
    c.family_status::text,
    c.created_at
  from public.citizens c
  left join public.families f on f.id = c.family_id
  where
    (
      nullif(trim(coalesce(p_name, '')), '') is null
      or lower(concat_ws(' ', coalesce(c.firstname, ''), coalesce(c.surname, ''), coalesce(c.username, ''))) like '%' || lower(trim(p_name)) || '%'
    )
    and (
      nullif(trim(coalesce(p_family_number, '')), '') is null
      or f.family_number = public.normalize_family_number(p_family_number)
    )
    and (
      nullif(trim(coalesce(p_family_status, '')), '') is null
      or c.family_status::text = upper(trim(p_family_status))
    )
  order by c.created_at desc;
$$;

grant execute on function public.api_get_citizens(text, text, text) to authenticated;

create or replace function public.api_get_families(
  p_family_number text default null,
  p_name text default null
)
returns table (
  id bigint,
  family_number text,
  address text,
  created_at timestamptz,
  member_count bigint
)
language sql
security definer
set search_path = public
as $$
  select
    f.id,
    f.family_number,
    f.address,
    f.created_at,
    count(c.id)::bigint as member_count
  from public.families f
  left join public.citizens c on c.family_id = f.id
  where
    (
      nullif(trim(coalesce(p_family_number, '')), '') is null
      or f.family_number = public.normalize_family_number(p_family_number)
    )
    and (
      nullif(trim(coalesce(p_name, '')), '') is null
      or exists (
        select 1
        from public.citizens c2
        where c2.family_id = f.id
          and lower(concat_ws(' ', coalesce(c2.firstname, ''), coalesce(c2.surname, ''), coalesce(c2.username, ''))) like '%' || lower(trim(p_name)) || '%'
      )
    )
  group by f.id, f.family_number, f.address, f.created_at
  order by f.family_number asc;
$$;

grant execute on function public.api_get_families(text, text) to authenticated;

create or replace function public.api_get_family_by_id(p_family_id bigint)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_result jsonb;
begin
  select jsonb_build_object(
    'id', f.id,
    'family_number', f.family_number,
    'address', f.address,
    'created_at', f.created_at,
    'members', coalesce(
      (
        select jsonb_agg(
          jsonb_build_object(
            'id', c.id,
            'username', c.username,
            'firstname', c.firstname,
            'surname', c.surname,
            'email', c.email,
            'contact_number', c.contact_number,
            'family_status', c.family_status::text,
            'created_at', c.created_at
          )
          order by c.created_at desc
        )
        from public.citizens c
        where c.family_id = f.id
      ),
      '[]'::jsonb
    )
  )
  into v_result
  from public.families f
  where f.id = p_family_id;

  return coalesce(v_result, jsonb_build_object('error', 'Family not found.'));
end;
$$;

grant execute on function public.api_get_family_by_id(bigint) to authenticated;

create or replace function public.api_upsert_citizen_family_assignment(
  p_citizen_id bigint,
  p_mode text,
  p_existing_family_id bigint default null,
  p_new_family_number text default null,
  p_new_family_address text default null
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_mode text;
  v_family_id bigint;
  v_exists boolean;
begin
  v_mode := upper(trim(coalesce(p_mode, '')));

  if p_citizen_id is null then
    return jsonb_build_object('ok', false, 'error', 'Citizen id is required.');
  end if;

  select exists (select 1 from public.citizens c where c.id = p_citizen_id)
  into v_exists;

  if not v_exists then
    return jsonb_build_object('ok', false, 'error', 'Citizen not found.');
  end if;

  if v_mode = 'NO_FAMILY_YET' then
    v_family_id := null;
  elsif v_mode = 'EXISTING_FAMILY' then
    if p_existing_family_id is null then
      return jsonb_build_object('ok', false, 'error', 'Existing family id is required.');
    end if;

    select f.id into v_family_id
    from public.families f
    where f.id = p_existing_family_id;

    if v_family_id is null then
      return jsonb_build_object('ok', false, 'error', 'Selected family does not exist.');
    end if;
  elsif v_mode = 'CREATE_FAMILY' then
    v_family_id := public.ensure_family(p_new_family_number, p_new_family_address);
    if v_family_id is null then
      return jsonb_build_object('ok', false, 'error', 'Family number is required for new family.');
    end if;
  else
    return jsonb_build_object('ok', false, 'error', 'Invalid mode. Use NO_FAMILY_YET, EXISTING_FAMILY, or CREATE_FAMILY.');
  end if;

  update public.citizens c
  set
    family_id = v_family_id,
    family_status = case
      when v_family_id is null then 'NO_FAMILY_YET'::public.family_status_enum
      else 'HAS_FAMILY'::public.family_status_enum
    end
  where c.id = p_citizen_id;

  return jsonb_build_object('ok', true, 'family_id', v_family_id);
end;
$$;

grant execute on function public.api_upsert_citizen_family_assignment(bigint, text, bigint, text, text) to authenticated;
