-- Appointments table to connect patients (citizens) with doctors (staff)
create table if not exists public.appointments (
  id bigint generated by default as identity primary key,
  citizen_id bigint not null references public.citizens(id) on delete cascade,
  doctor_staff_id bigint not null references public.staff(id) on delete cascade,
  appointment_date date not null,
  appointment_time time not null,
  status varchar(50) not null default 'pending' check (status in ('pending', 'confirmed', 'completed', 'cancelled', 'no-show')),
  patient_notes text,
  doctor_notes text,
  cancellation_reason text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  created_by uuid,
  cancelled_by uuid,
  cancelled_at timestamptz
);

-- Index for faster queries
create index idx_appointments_citizen_id on public.appointments(citizen_id);
create index idx_appointments_doctor_staff_id on public.appointments(doctor_staff_id);
create index idx_appointments_date on public.appointments(appointment_date);
create index idx_appointments_status on public.appointments(status);

-- Enable RLS
alter table public.appointments enable row level security;

-- RLS Policies

-- Patients (citizens) can view their own appointments
create policy "citizens_view_own_appointments"
on public.appointments for select
using (
  auth.uid() = (select auth_user_id from public.citizens where id = citizen_id)
);

-- Patients can create appointments
create policy "citizens_create_appointments"
on public.appointments for insert
with check (
  auth.uid() = (select auth_user_id from public.citizens where id = citizen_id)
);

-- Patients can update their own pending/confirmed appointments (notes only)
create policy "citizens_update_own_appointments"
on public.appointments for update
using (
  auth.uid() = (select auth_user_id from public.citizens where id = citizen_id)
  and status in ('pending', 'confirmed')
)
with check (
  auth.uid() = (select auth_user_id from public.citizens where id = citizen_id)
  and status in ('pending', 'confirmed')
);

-- Doctors can view appointments assigned to them
create policy "doctors_view_assigned_appointments"
on public.appointments for select
using (
  auth.uid() = (select auth_user_id from public.staff where id = doctor_staff_id)
);

-- Doctors can update notes and status on their appointments
create policy "doctors_update_appointments"
on public.appointments for update
using (
  auth.uid() = (select auth_user_id from public.staff where id = doctor_staff_id)
)
with check (
  auth.uid() = (select auth_user_id from public.staff where id = doctor_staff_id)
);

-- Staff/Admin can view all appointments (via check)
create policy "staff_view_all_appointments"
on public.appointments for select
using (
  exists (
    select 1 from public.staff 
    where auth_user_id = auth.uid() 
    and (role = 'admin' or role = 'staff' or role = 'doctor')
  )
);

-- Staff/Admin can manage all appointments
create policy "staff_manage_appointments"
on public.appointments for all
using (
  exists (
    select 1 from public.staff 
    where auth_user_id = auth.uid() 
    and role = 'admin'
  )
)
with check (
  exists (
    select 1 from public.staff 
    where auth_user_id = auth.uid() 
    and role = 'admin'
  )
);

-- Helper function to get available doctor time slots
create or replace function public.get_available_doctor_slots(
  p_doctor_staff_id bigint,
  p_date_from date default current_date,
  p_date_to date default (current_date + interval '30 days')::date
)
returns table (
  appointment_date date,
  appointment_time time,
  doctor_name varchar,
  specialization varchar
) as $$
declare
  v_doctor record;
begin
  -- Get doctor details
  select first_name, last_name, 
         (staff.id #>> '{}'->'doctor_specialization')::varchar as spec
  into v_doctor
  from public.staff
  where id = p_doctor_staff_id and role = 'doctor';
  
  if v_doctor is null then
    return;
  end if;
  
  -- Return available slots from doctor_schedules minus appointments
  return query
  select 
    ds.schedule_date::date as appointment_date,
    ds.start_time::time as appointment_time,
    concat(v_doctor.first_name, ' ', v_doctor.last_name) as doctor_name,
    coalesce(staff.doctor_specialization, '') as specialization
  from public.doctor_schedules ds
  left join public.staff on staff.id = ds.doctor_staff_id
  left join public.appointments a on 
    a.doctor_staff_id = ds.doctor_staff_id 
    and a.appointment_date = ds.schedule_date::date
    and a.appointment_time = ds.start_time::time
    and a.status != 'cancelled'
  where 
    ds.doctor_staff_id = p_doctor_staff_id
    and ds.schedule_date::date >= p_date_from
    and ds.schedule_date::date <= p_date_to
    and a.id is null -- Only show slots without appointments
  order by ds.schedule_date, ds.start_time;
end;
$$ language plpgsql security invoker;

-- Function to book appointment (used by mobile/web)
create or replace function public.book_appointment(
  p_citizen_id bigint,
  p_doctor_staff_id bigint,
  p_appointment_date date,
  p_appointment_time time,
  p_patient_notes text default null
)
returns json as $$
declare
  v_appointment_id bigint;
  v_error_message text;
  v_existing_count int;
begin
  -- Validate doctor exists and is active
  if not exists (select 1 from public.staff where id = p_doctor_staff_id and role = 'doctor' and status = 'Active') then
    return json_build_object('success', false, 'error', 'Doctor not found or inactive');
  end if;
  
  -- Validate citizen exists
  if not exists (select 1 from public.citizens where id = p_citizen_id) then
    return json_build_object('success', false, 'error', 'Patient not found');
  end if;
  
  -- Check if slot is available
  select count(*) into v_existing_count
  from public.appointments
  where doctor_staff_id = p_doctor_staff_id
    and appointment_date = p_appointment_date
    and appointment_time = p_appointment_time
    and status != 'cancelled';
  
  if v_existing_count > 0 then
    return json_build_object('success', false, 'error', 'This time slot is no longer available');
  end if;
  
  -- Check if doctor has schedule for this slot
  if not exists (
    select 1 from public.doctor_schedules
    where doctor_staff_id = p_doctor_staff_id
      and schedule_date::date = p_appointment_date
      and start_time::time = p_appointment_time
  ) then
    return json_build_object('success', false, 'error', 'Doctor does not have availability at this time');
  end if;
  
  -- Create appointment
  insert into public.appointments (
    citizen_id, doctor_staff_id, appointment_date, appointment_time,
    status, patient_notes, created_by
  ) values (
    p_citizen_id, p_doctor_staff_id, p_appointment_date, p_appointment_time,
    'pending', p_patient_notes, auth.uid()
  )
  returning id into v_appointment_id;
  
  return json_build_object(
    'success', true,
    'appointment_id', v_appointment_id,
    'message', 'Appointment booked successfully. Awaiting doctor confirmation.'
  );
exception when others then
  return json_build_object('success', false, 'error', sqlerrm);
end;
$$ language plpgsql security invoker;

-- Function to list appointments for patients
create or replace function public.list_my_appointments()
returns table (
  id bigint,
  appointment_date date,
  appointment_time time,
  doctor_name varchar,
  specialization varchar,
  status varchar,
  patient_notes text
) as $$
begin
  return query
  select 
    a.id,
    a.appointment_date,
    a.appointment_time,
    concat(s.first_name, ' ', s.last_name) as doctor_name,
    coalesce(s.doctor_specialization, '') as specialization,
    a.status,
    a.patient_notes
  from public.appointments a
  join public.staff s on s.id = a.doctor_staff_id
  where a.citizen_id = (
    select id from public.citizens where auth_user_id = auth.uid()
  )
  order by a.appointment_date desc, a.appointment_time desc;
end;
$$ language plpgsql security invoker;

-- Function for doctors to list their appointments
create or replace function public.list_doctor_appointments(
  p_status varchar default null,
  p_date_from date default null,
  p_date_to date default null
)
returns table (
  id bigint,
  appointment_date date,
  appointment_time time,
  patient_name varchar,
  patient_email varchar,
  contact_number varchar,
  status varchar,
  patient_notes text,
  doctor_notes text
) as $$
begin
  return query
  select 
    a.id,
    a.appointment_date,
    a.appointment_time,
    concat(c.firstname, ' ', c.surname) as patient_name,
    c.email as patient_email,
    c.contact_number,
    a.status,
    a.patient_notes,
    a.doctor_notes
  from public.appointments a
  join public.citizens c on c.id = a.citizen_id
  where a.doctor_staff_id = (
    select id from public.staff where auth_user_id = auth.uid()
  )
  and (p_status is null or a.status = p_status)
  and (p_date_from is null or a.appointment_date >= p_date_from)
  and (p_date_to is null or a.appointment_date <= p_date_to)
  order by a.appointment_date desc, a.appointment_time desc;
end;
$$ language plpgsql security invoker;

-- Function for admin to list all appointments
create or replace function public.list_all_appointments(
  p_status varchar default null,
  p_date_from date default null,
  p_date_to date default null,
  p_doctor_staff_id bigint default null
)
returns table (
  id bigint,
  appointment_date date,
  appointment_time time,
  patient_name varchar,
  patient_email varchar,
  doctor_name varchar,
  doctor_specialization varchar,
  status varchar,
  patient_notes text,
  doctor_notes text,
  created_at timestamptz
) as $$
begin
  return query
  select 
    a.id,
    a.appointment_date,
    a.appointment_time,
    concat(c.firstname, ' ', c.surname) as patient_name,
    c.email as patient_email,
    concat(s.first_name, ' ', s.last_name) as doctor_name,
    coalesce(s.doctor_specialization, '') as doctor_specialization,
    a.status,
    a.patient_notes,
    a.doctor_notes,
    a.created_at
  from public.appointments a
  join public.citizens c on c.id = a.citizen_id
  join public.staff s on s.id = a.doctor_staff_id
  where (p_status is null or a.status = p_status)
  and (p_date_from is null or a.appointment_date >= p_date_from)
  and (p_date_to is null or a.appointment_date <= p_date_to)
  and (p_doctor_staff_id is null or a.doctor_staff_id = p_doctor_staff_id)
  order by a.appointment_date desc, a.appointment_time desc;
end;
$$ language plpgsql security invoker;
