-- Migration: 20260902130000_system_resilience_and_hardening.sql
-- Description: System resilience hardening addressing critical operational edge cases:
--   1. Medicine ID linkage on prescription items (eliminating text-matching failures)
--   2. Expiration date safety guards on prescription & OTC dispensing
--   3. Audit-backed medicine returns & inventory restocking workflow
--   4. Non-app walk-in patient support for queue tickets

-- ── 1. Prescription Items Medicine ID Linkage ──────────────────────────────────
alter table public.prescription_items
  add column if not exists medicine_id bigint references public.medicines(id) on delete set null;

create index if not exists idx_prescription_items_medicine_id
  on public.prescription_items (medicine_id);

-- Backfill medicine_id from medicines table
update public.prescription_items pi
set medicine_id = m.id
from public.medicines m
where pi.medicine_id is null
  and lower(trim(pi.medicine_name)) = lower(trim(m.name))
  and m.archived_at is null;

-- ── 2. Add Returned Quantity Tracking ──────────────────────────────────────────
alter table public.prescription_items
  add column if not exists returned_quantity integer not null default 0
    check (returned_quantity >= 0);

alter table public.otc_dispense_items
  add column if not exists returned_quantity integer not null default 0
    check (returned_quantity >= 0);

-- ── 3. Dispense Returns Audit Table ───────────────────────────────────────────
create table if not exists public.dispense_returns (
  id bigint generated by default as identity primary key,
  return_type text not null check (return_type in ('prescription', 'otc')),
  prescription_item_id bigint references public.prescription_items(id) on delete set null,
  otc_item_id bigint references public.otc_dispense_items(id) on delete set null,
  medicine_id bigint not null references public.medicines(id),
  quantity integer not null check (quantity > 0),
  reason text not null,
  returned_by_staff_id bigint not null references public.staff(id),
  returned_at timestamptz not null default now()
);

create index if not exists idx_dispense_returns_med on public.dispense_returns(medicine_id);
create index if not exists idx_dispense_returns_staff on public.dispense_returns(returned_by_staff_id);
create index if not exists idx_dispense_returns_rx_item on public.dispense_returns(prescription_item_id);

alter table public.dispense_returns enable row level security;

drop policy if exists dispense_returns_select_staff on public.dispense_returns;
create policy dispense_returns_select_staff
  on public.dispense_returns
  for select
  using (
    exists (
      select 1 from public.staff s
      where s.auth_user_id = auth.uid()
        and s.status = 'active'
    )
  );

grant select, insert on public.dispense_returns to authenticated;

-- ── 4. Walk-in Support for Queue Tickets ───────────────────────────────────────
alter table public.queue_tickets
  alter column citizen_id drop not null;

alter table public.queue_tickets
  add column if not exists walkin_patient_name text;

-- Update select policy on queue tickets to allow staff access and citizen access
drop policy if exists queue_tickets_select_policy on public.queue_tickets;
create policy queue_tickets_select_policy
  on public.queue_tickets
  for select
  using (
    -- Staff can view all queue tickets
    exists (
      select 1 from public.staff s
      where s.auth_user_id = auth.uid()
        and s.status = 'active'
    )
    or
    -- Citizens can view their own queue tickets
    (
      citizen_id is not null and exists (
        select 1 from public.citizens c
        where c.id = queue_tickets.citizen_id
          and c.auth_user_id = auth.uid()
      )
    )
  );

-- ── 5. Hardened Dispense Prescription Items RPC ────────────────────────────────
create or replace function public.dispense_prescription_items(
  p_prescription_code text,
  p_items jsonb,
  p_note text default null
)
returns json
language plpgsql
security definer
set search_path = public
as $$
declare
  v_staff_id bigint;
  v_role text;
  v_header_id bigint;
  v_header_status text;
  v_row record;
  v_item record;
  v_medicine_id bigint;
  v_medicine_qty integer;
  v_medicine_expiry date;
  v_new_status text;
  v_total_rows integer;
begin
  -- Resolve caller
  select s.id, s.role
  into v_staff_id, v_role
  from public.staff s
  where s.auth_user_id = auth.uid()
    and s.status = 'active'
  limit 1;

  if v_staff_id is null then
    return json_build_object('error', 'Not authenticated as active staff');
  end if;

  if v_role <> 'pharmacist' then
    return json_build_object('error', 'Forbidden: only pharmacists can dispense prescriptions');
  end if;

  if p_items is null or jsonb_typeof(p_items) <> 'array' or jsonb_array_length(p_items) = 0 then
    return json_build_object('error', 'No dispense items provided');
  end if;

  begin
    -- Lock target prescription
    select ph.id, ph.dispensing_status
    into v_header_id, v_header_status
    from public.prescription_headers ph
    where upper(trim(ph.prescription_code)) = upper(trim(coalesce(p_prescription_code, '')))
    limit 1
    for update;

    if v_header_id is null then
      raise exception 'Prescription not found';
    end if;

    if v_header_status = 'cancelled' then
      raise exception 'Prescription has been cancelled and cannot be dispensed';
    end if;

    if v_header_status = 'expired' then
      raise exception 'Prescription has expired and can no longer be dispensed';
    end if;

    if v_header_status = 'dispensed' then
      raise exception 'Prescription is already fully dispensed';
    end if;

    -- Disallow duplicate item IDs in request payload
    if exists (
      select 1
      from jsonb_to_recordset(p_items) as r(prescription_item_id bigint, quantity integer)
      group by r.prescription_item_id
      having count(*) > 1
    ) then
      raise exception 'Duplicate prescription_item_id in request payload';
    end if;

    for v_row in
      select r.prescription_item_id, r.quantity
      from jsonb_to_recordset(p_items) as r(prescription_item_id bigint, quantity integer)
    loop
      if v_row.prescription_item_id is null then
        raise exception 'prescription_item_id is required for every item';
      end if;

      if v_row.quantity is null or v_row.quantity < 0 then
        raise exception 'Dispense quantity cannot be negative for item %', v_row.prescription_item_id;
      end if;

      if v_row.quantity = 0 then
        continue;
      end if;

      select
        pi.id,
        pi.medicine_id,
        pi.medicine_name,
        pi.unit,
        pi.quantity,
        coalesce(pi.dispensed_quantity, 0) as dispensed_quantity,
        coalesce(pi.remaining_quantity, pi.quantity - coalesce(pi.dispensed_quantity, 0)) as remaining_quantity
      into v_item
      from public.prescription_items pi
      where pi.id = v_row.prescription_item_id
        and pi.prescription_id = v_header_id
      for update;

      if v_item.id is null then
        raise exception 'Prescription item % not found for this prescription', v_row.prescription_item_id;
      end if;

      if v_row.quantity > v_item.remaining_quantity then
        raise exception
          'Over-dispense blocked for % (remaining: %, requested: %)',
          v_item.medicine_name, v_item.remaining_quantity, v_row.quantity;
      end if;

      -- Smart match: match by medicine_id first, then fallback to name
      select m.id, m.qty, m.expiry_date
      into v_medicine_id, v_medicine_qty, v_medicine_expiry
      from public.medicines m
      where (
        (v_item.medicine_id is not null and m.id = v_item.medicine_id)
        or lower(trim(m.name)) = lower(trim(v_item.medicine_name))
      )
      and m.archived_at is null
      order by (case when v_item.medicine_id is not null and m.id = v_item.medicine_id then 0 else 1 end) asc, m.id asc
      limit 1
      for update;

      if v_medicine_id is null then
        raise exception 'Medicine not found in inventory: %', v_item.medicine_name;
      end if;

      -- Safety Guard: Block dispensing of expired batch
      if v_medicine_expiry is not null and v_medicine_expiry < current_date then
        raise exception 'Safety block: Inventory batch for % expired on % and cannot be dispensed.',
          v_item.medicine_name, to_char(v_medicine_expiry, 'YYYY-MM-DD');
      end if;

      if v_medicine_qty < v_row.quantity then
        raise exception
          'Insufficient stock for % (available: %, requested: %)',
          v_item.medicine_name, v_medicine_qty, v_row.quantity;
      end if;

      -- Deduct inventory stock
      update public.medicines
      set qty = qty - v_row.quantity
      where id = v_medicine_id;

      -- Update item dispensed & remaining counters
      update public.prescription_items
      set
        medicine_id = coalesce(v_item.medicine_id, v_medicine_id),
        dispensed_quantity = v_item.dispensed_quantity + v_row.quantity,
        remaining_quantity = v_item.remaining_quantity - v_row.quantity,
        is_dispensed = (v_item.remaining_quantity - v_row.quantity = 0)
      where id = v_item.id;

      -- Record dispense event
      insert into public.prescription_item_dispenses (
        prescription_item_id,
        dispensed_quantity,
        dispensed_by_staff_id,
        note
      ) values (
        v_item.id,
        v_row.quantity,
        v_staff_id,
        nullif(trim(p_note), '')
      );
    end loop;

    -- Recalculate prescription header status
    select
      count(*),
      count(*) filter (where remaining_quantity = 0),
      count(*) filter (where remaining_quantity > 0 and dispensed_quantity > 0)
    into v_total_rows, v_medicine_qty, v_medicine_id
    from public.prescription_items
    where prescription_id = v_header_id;

    if v_total_rows = 0 then
      v_new_status := 'pending';
    elsif v_medicine_qty = v_total_rows then
      v_new_status := 'dispensed';
    elsif v_medicine_qty > 0 or v_medicine_id > 0 then
      v_new_status := 'partially_dispensed';
    else
      v_new_status := 'pending';
    end if;

    update public.prescription_headers
    set
      dispensing_status = v_new_status,
      dispensed_by_staff_id = v_staff_id,
      dispensed_at = case when v_new_status = 'dispensed' then now() else dispensed_at end
    where id = v_header_id;

    return json_build_object(
      'ok', true,
      'prescription_code', upper(trim(p_prescription_code)),
      'dispensing_status', v_new_status
    );
  exception
    when others then
      return json_build_object('error', sqlerrm);
  end;
end;
$$;

-- ── 6. Hardened OTC Dispensing RPC with Expiration Safety ─────────────────────
create or replace function public.dispense_otc_medicines(
  p_citizen_id bigint default null,
  p_patient_name text default null,
  p_items jsonb default '[]'::jsonb,
  p_notes text default null
)
returns json
language plpgsql
security definer
set search_path = public
as $$
declare
  v_staff_id bigint;
  v_role text;
  v_dispense_id bigint;
  v_ref_no text;
  v_date_str text;
  v_random_suffix text;
  v_row record;
  v_med record;
  v_items_count integer := 0;
begin
  select s.id, s.role into v_staff_id, v_role
  from public.staff s
  where s.auth_user_id = auth.uid() and s.status = 'active'
  limit 1;

  if v_staff_id is null then
    return json_build_object('error', 'Not authenticated as active staff.');
  end if;

  if v_role <> 'pharmacist' then
    return json_build_object('error', 'Forbidden: only pharmacists can dispense medicines.');
  end if;

  if p_items is null or jsonb_typeof(p_items) <> 'array' or jsonb_array_length(p_items) = 0 then
    return json_build_object('error', 'No medicines selected for dispensing.');
  end if;

  v_date_str := to_char(timezone('Asia/Manila', now()), 'YYYYMMDD');
  v_random_suffix := lpad(floor(random() * 9000 + 1000)::text, 4, '0');
  v_ref_no := 'OTC-' || v_date_str || '-' || v_random_suffix;

  insert into public.otc_dispenses (
    reference_no,
    citizen_id,
    walkin_patient_name,
    dispensed_by_staff_id,
    dispensed_at,
    notes
  ) values (
    v_ref_no,
    p_citizen_id,
    trim(coalesce(nullif(p_patient_name, ''), 'Walk-in Patient')),
    v_staff_id,
    now(),
    p_notes
  ) returning id into v_dispense_id;

  for v_row in
    select r.medicine_id, r.quantity, r.instructions
    from jsonb_to_recordset(p_items) as r(medicine_id bigint, quantity integer, instructions text)
  loop
    if v_row.medicine_id is null then
      raise exception 'medicine_id is required for every item.';
    end if;

    if v_row.quantity is null or v_row.quantity <= 0 then
      continue;
    end if;

    select m.id, m.name, m.qty, m.unit, m.drug_classification, m.expiry_date
    into v_med
    from public.medicines m
    where m.id = v_row.medicine_id and m.archived_at is null
    for update;

    if v_med.id is null then
      raise exception 'Medicine ID % not found in inventory.', v_row.medicine_id;
    end if;

    if v_med.drug_classification <> 'otc' then
      raise exception '% is classified as Prescription-Only (Rx) and cannot be dispensed over-the-counter.', v_med.name;
    end if;

    -- Safety Guard: Block dispensing of expired batch
    if v_med.expiry_date is not null and v_med.expiry_date < current_date then
      raise exception 'Safety block: Inventory for % expired on % and cannot be dispensed.',
        v_med.name, to_char(v_med.expiry_date, 'YYYY-MM-DD');
    end if;

    if v_med.qty < v_row.quantity then
      raise exception 'Insufficient stock for % (Available: %, Requested: %).', v_med.name, v_med.qty, v_row.quantity;
    end if;

    update public.medicines
    set qty = qty - v_row.quantity
    where id = v_med.id;

    insert into public.otc_dispense_items (
      otc_dispense_id,
      medicine_id,
      quantity,
      unit,
      instructions
    ) values (
      v_dispense_id,
      v_med.id,
      v_row.quantity,
      coalesce(v_med.unit, ''),
      v_row.instructions
    );

    v_items_count := v_items_count + 1;
  end loop;

  if v_items_count = 0 then
    raise exception 'No items with quantity > 0 were dispensed.';
  end if;

  return json_build_object(
    'ok', true,
    'reference_no', v_ref_no,
    'otc_dispense_id', v_dispense_id,
    'items_count', v_items_count
  );
exception when others then
  return json_build_object('error', SQLERRM);
end;
$$;

-- ── 7. Return & Restock RPC for Prescription Items ─────────────────────────────
create or replace function public.return_dispensed_prescription_item(
  p_prescription_item_id bigint,
  p_quantity integer,
  p_reason text
)
returns json
language plpgsql
security definer
set search_path = public
as $$
declare
  v_staff_id bigint;
  v_role text;
  v_item record;
  v_header record;
  v_med_id bigint;
  v_active_dispensed integer;
  v_new_status text;
  v_total_rows integer;
  v_full_count integer;
  v_part_count integer;
begin
  select s.id, s.role into v_staff_id, v_role
  from public.staff s
  where s.auth_user_id = auth.uid() and s.status = 'active'
  limit 1;

  if v_staff_id is null then
    return json_build_object('error', 'Not authenticated as active staff.');
  end if;

  if v_role <> 'pharmacist' then
    return json_build_object('error', 'Forbidden: only pharmacists can restock returned items.');
  end if;

  if p_quantity is null or p_quantity <= 0 then
    return json_build_object('error', 'Return quantity must be greater than 0.');
  end if;

  if trim(coalesce(p_reason, '')) = '' then
    return json_build_object('error', 'A return reason is required.');
  end if;

  -- Lock item
  select *
  into v_item
  from public.prescription_items
  where id = p_prescription_item_id
  for update;

  if v_item.id is null then
    return json_build_object('error', 'Prescription item not found.');
  end if;

  v_active_dispensed := v_item.dispensed_quantity - coalesce(v_item.returned_quantity, 0);

  if p_quantity > v_active_dispensed then
    return json_build_object('error', format('Cannot return %s units; only %s units are currently dispensed.', p_quantity, v_active_dispensed));
  end if;

  -- Resolve medicine for restocking
  select m.id into v_med_id
  from public.medicines m
  where (
    (v_item.medicine_id is not null and m.id = v_item.medicine_id)
    or lower(trim(m.name)) = lower(trim(v_item.medicine_name))
  )
  and m.archived_at is null
  order by (case when v_item.medicine_id is not null and m.id = v_item.medicine_id then 0 else 1 end) asc, m.id asc
  limit 1
  for update;

  if v_med_id is null then
    return json_build_object('error', format('Medicine %s not found in inventory for restocking.', v_item.medicine_name));
  end if;

  -- Restock inventory
  update public.medicines
  set qty = qty + p_quantity
  where id = v_med_id;

  -- Update prescription item counters
  update public.prescription_items
  set
    returned_quantity = coalesce(returned_quantity, 0) + p_quantity,
    dispensed_quantity = greatest(0, dispensed_quantity - p_quantity),
    remaining_quantity = least(quantity, remaining_quantity + p_quantity),
    is_dispensed = false
  where id = v_item.id;

  -- Log return audit record
  insert into public.dispense_returns (
    return_type,
    prescription_item_id,
    medicine_id,
    quantity,
    reason,
    returned_by_staff_id,
    returned_at
  ) values (
    'prescription',
    v_item.id,
    v_med_id,
    p_quantity,
    trim(p_reason),
    v_staff_id,
    now()
  );

  -- Recalculate header status
  select
    count(*),
    count(*) filter (where remaining_quantity = 0),
    count(*) filter (where remaining_quantity > 0 and dispensed_quantity > 0)
  into v_total_rows, v_full_count, v_part_count
  from public.prescription_items
  where prescription_id = v_item.prescription_id;

  if v_full_count = v_total_rows and v_total_rows > 0 then
    v_new_status := 'dispensed';
  elsif v_full_count > 0 or v_part_count > 0 then
    v_new_status := 'partially_dispensed';
  else
    v_new_status := 'pending';
  end if;

  update public.prescription_headers
  set dispensing_status = v_new_status
  where id = v_item.prescription_id;

  return json_build_object(
    'ok', true,
    'message', format('Restocked %s units of %s.', p_quantity, v_item.medicine_name),
    'dispensing_status', v_new_status
  );
exception when others then
  return json_build_object('error', SQLERRM);
end;
$$;

-- ── 8. Return & Restock RPC for OTC Dispenses ──────────────────────────────────
create or replace function public.return_otc_dispensed_item(
  p_otc_item_id bigint,
  p_quantity integer,
  p_reason text
)
returns json
language plpgsql
security definer
set search_path = public
as $$
declare
  v_staff_id bigint;
  v_role text;
  v_item record;
  v_active_dispensed integer;
begin
  select s.id, s.role into v_staff_id, v_role
  from public.staff s
  where s.auth_user_id = auth.uid() and s.status = 'active'
  limit 1;

  if v_staff_id is null then
    return json_build_object('error', 'Not authenticated as active staff.');
  end if;

  if v_role <> 'pharmacist' then
    return json_build_object('error', 'Forbidden: only pharmacists can restock returned items.');
  end if;

  if p_quantity is null or p_quantity <= 0 then
    return json_build_object('error', 'Return quantity must be greater than 0.');
  end if;

  if trim(coalesce(p_reason, '')) = '' then
    return json_build_object('error', 'A return reason is required.');
  end if;

  select *
  into v_item
  from public.otc_dispense_items
  where id = p_otc_item_id
  for update;

  if v_item.id is null then
    return json_build_object('error', 'OTC dispense item not found.');
  end if;

  v_active_dispensed := v_item.quantity - coalesce(v_item.returned_quantity, 0);

  if p_quantity > v_active_dispensed then
    return json_build_object('error', format('Cannot return %s units; only %s units are eligible for return.', p_quantity, v_active_dispensed));
  end if;

  -- Restock inventory
  update public.medicines
  set qty = qty + p_quantity
  where id = v_item.medicine_id;

  -- Update item
  update public.otc_dispense_items
  set returned_quantity = coalesce(returned_quantity, 0) + p_quantity
  where id = v_item.id;

  -- Audit log
  insert into public.dispense_returns (
    return_type,
    otc_item_id,
    medicine_id,
    quantity,
    reason,
    returned_by_staff_id,
    returned_at
  ) values (
    'otc',
    v_item.id,
    v_item.medicine_id,
    p_quantity,
    trim(p_reason),
    v_staff_id,
    now()
  );

  return json_build_object(
    'ok', true,
    'message', format('Restocked %s units to inventory.', p_quantity)
  );
exception when others then
  return json_build_object('error', SQLERRM);
end;
$$;

grant execute on function public.return_dispensed_prescription_item(bigint, integer, text) to authenticated;
grant execute on function public.return_otc_dispensed_item(bigint, integer, text) to authenticated;
