-- Create staff login/logout logging tracking for audit and export capabilities.

CREATE TABLE IF NOT EXISTS public.staff_login_logs (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  staff_id bigint REFERENCES public.staff(id) ON DELETE CASCADE,
  username text NOT NULL,
  email text NOT NULL,
  role text NOT NULL,
  action text NOT NULL CONSTRAINT check_staff_action CHECK (action IN ('login', 'logout')),
  logged_at timestamptz DEFAULT now() NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_staff_login_logs_logged_at ON public.staff_login_logs(logged_at DESC);
CREATE INDEX IF NOT EXISTS idx_staff_login_logs_staff_id ON public.staff_login_logs(staff_id);

-- Enable RLS
ALTER TABLE public.staff_login_logs ENABLE ROW LEVEL SECURITY;

-- Allow authenticated doctors/nurses (is_admin()) to select logs
DROP POLICY IF EXISTS select_staff_login_logs ON public.staff_login_logs;
CREATE POLICY select_staff_login_logs ON public.staff_login_logs
  FOR SELECT
  USING (public.is_admin());

-- RPC to record login/logout action for the currently authenticated staff account
CREATE OR REPLACE FUNCTION public.log_staff_action(p_action text)
RETURNS boolean
LANGUAGE plpgsql
SECURITY DEFINER
VOLATILE
AS $$
DECLARE
  v_user_id uuid;
  v_user_email text;
  v_staff_id bigint;
  v_username text;
  v_role text;
  v_logged_at timestamptz;
BEGIN
  v_user_id := auth.uid();
  v_user_email := lower(coalesce(auth.jwt()->>'email', ''));

  IF v_user_id IS NULL AND v_user_email = '' THEN
    RETURN false;
  END IF;

  -- Resolve staff details
  SELECT id, username, role INTO v_staff_id, v_username, v_role
  FROM public.staff
  WHERE (v_user_id IS NOT NULL AND auth_user_id = v_user_id)
     OR (v_user_email <> '' AND lower(email) = v_user_email);

  IF v_staff_id IS NULL THEN
    RETURN false;
  END IF;

  -- Ensure we insert in Asia/Manila (UTC+8) time timezone
  v_logged_at := timezone('Asia/Manila', now());

  INSERT INTO public.staff_login_logs (staff_id, username, email, role, action, logged_at)
  VALUES (v_staff_id, v_username, coalesce(v_user_email, ''), v_role, p_action, v_logged_at);

  RETURN true;
END;
$$;

-- Grant execution permissions
GRANT EXECUTE ON FUNCTION public.log_staff_action(text) TO authenticated;
