-- Consultation -> Prescription -> Inventory/Dosage flow hardening.
--
-- This migration adds:
-- 1) Rich prescription item fields (dosage/frequency/duration/instructions)
-- 2) Inventory transaction ledger
-- 3) Generated dosage schedule rows for mobile
-- 4) Atomic stock deduction on prescription item insert
-- 5) Mobile RPC response includes dosage fields

alter table if exists public.prescription_items
  add column if not exists dosage text,
  add column if not exists frequency text,
  add column if not exists duration_days integer,
  add column if not exists instructions text,
  add column if not exists additional_info text;

alter table if exists public.prescription_items
  drop constraint if exists prescription_items_duration_days_positive;

alter table if exists public.prescription_items
  add constraint prescription_items_duration_days_positive
  check (duration_days is null or duration_days > 0);

create table if not exists public.medicine_inventory_transactions (
  id bigint generated by default as identity primary key,
  medicine_id bigint not null references public.medicines(id) on delete cascade,
  medicine_name text not null,
  change_qty integer not null,
  resulting_qty integer not null,
  reason text not null,
  prescription_item_id bigint references public.prescription_items(id) on delete set null,
  doctor_staff_id bigint references public.staff(id) on delete set null,
  created_at timestamptz not null default now(),
  constraint medicine_inventory_transactions_reason_non_empty check (length(trim(reason)) > 0)
);

create index if not exists idx_medicine_inventory_transactions_medicine_id
  on public.medicine_inventory_transactions(medicine_id, created_at desc);
create index if not exists idx_medicine_inventory_transactions_prescription_item_id
  on public.medicine_inventory_transactions(prescription_item_id);

create table if not exists public.prescription_dosage_schedules (
  id bigint generated by default as identity primary key,
  prescription_item_id bigint not null references public.prescription_items(id) on delete cascade,
  citizen_id bigint references public.citizens(id) on delete set null,
  medicine_name text not null,
  dosage text,
  frequency text,
  instructions text,
  schedule_date date not null,
  dose_time time not null,
  status text not null default 'pending',
  taken_at timestamptz,
  created_at timestamptz not null default now(),
  constraint prescription_dosage_schedules_status_valid check (status in ('pending', 'taken', 'missed'))
);

create index if not exists idx_prescription_dosage_schedules_citizen_date
  on public.prescription_dosage_schedules(citizen_id, schedule_date, dose_time);
create index if not exists idx_prescription_dosage_schedules_item
  on public.prescription_dosage_schedules(prescription_item_id);

alter table public.medicine_inventory_transactions enable row level security;
alter table public.prescription_dosage_schedules enable row level security;

drop policy if exists medicine_inventory_transactions_select_active_staff on public.medicine_inventory_transactions;
create policy medicine_inventory_transactions_select_active_staff
  on public.medicine_inventory_transactions
  for select
  using (
    public.is_admin()
    or exists (
      select 1
      from public.staff s
      where s.auth_user_id = auth.uid()
        and lower(trim(coalesce(s.status, ''))) = 'active'
    )
  );

drop policy if exists medicine_inventory_transactions_insert_doctor on public.medicine_inventory_transactions;
create policy medicine_inventory_transactions_insert_doctor
  on public.medicine_inventory_transactions
  for insert
  with check (
    public.is_admin()
    or exists (
      select 1
      from public.staff s
      where s.auth_user_id = auth.uid()
        and lower(trim(coalesce(s.status, ''))) = 'active'
        and lower(trim(coalesce(s.role, ''))) = 'doctor'
    )
  );

drop policy if exists prescription_dosage_schedules_select_active_staff on public.prescription_dosage_schedules;
create policy prescription_dosage_schedules_select_active_staff
  on public.prescription_dosage_schedules
  for select
  using (
    public.is_admin()
    or exists (
      select 1
      from public.staff s
      where s.auth_user_id = auth.uid()
        and lower(trim(coalesce(s.status, ''))) = 'active'
    )
  );

drop policy if exists prescription_dosage_schedules_select_own_citizen on public.prescription_dosage_schedules;
create policy prescription_dosage_schedules_select_own_citizen
  on public.prescription_dosage_schedules
  for select
  using (
    exists (
      select 1
      from public.citizens c
      where c.id = prescription_dosage_schedules.citizen_id
        and c.auth_user_id = auth.uid()
    )
  );

drop policy if exists prescription_dosage_schedules_insert_doctor on public.prescription_dosage_schedules;
create policy prescription_dosage_schedules_insert_doctor
  on public.prescription_dosage_schedules
  for insert
  with check (
    public.is_admin()
    or exists (
      select 1
      from public.prescription_items pi
      join public.prescription_headers ph on ph.id = pi.prescription_id
      join public.staff s on s.id = ph.doctor_staff_id
      where pi.id = prescription_dosage_schedules.prescription_item_id
        and s.auth_user_id = auth.uid()
        and lower(trim(coalesce(s.status, ''))) = 'active'
        and lower(trim(coalesce(s.role, ''))) = 'doctor'
    )
  );

grant select, insert on public.medicine_inventory_transactions to authenticated;
grant select, insert on public.prescription_dosage_schedules to authenticated;

create or replace function public.get_frequency_times(p_frequency text)
returns time[]
language plpgsql
immutable
as $$
declare
  v_frequency text := lower(trim(coalesce(p_frequency, '')));
begin
  if v_frequency = '' then
    return array['08:00'::time];
  end if;

  if v_frequency like '%every 6%' then
    return array['06:00'::time, '12:00'::time, '18:00'::time, '00:00'::time];
  end if;

  if v_frequency like '%every 8%' then
    return array['06:00'::time, '14:00'::time, '22:00'::time];
  end if;

  if v_frequency like '%three%' or v_frequency like '%3x%' or v_frequency like '%thrice%' then
    return array['08:00'::time, '14:00'::time, '20:00'::time];
  end if;

  if v_frequency like '%twice%' or v_frequency like '%2x%' then
    return array['08:00'::time, '20:00'::time];
  end if;

  return array['08:00'::time];
end;
$$;

create or replace function public.handle_prescription_item_stock_and_schedule()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  v_medicine_row public.medicines%rowtype;
  v_now timestamptz := now();
  v_doctor_staff_id bigint;
  v_citizen_id bigint;
  v_duration_days integer;
  v_day_offset integer;
  v_times time[];
  v_time time;
begin
  if new.quantity is null or new.quantity <= 0 then
    raise exception 'Prescription quantity must be greater than zero.';
  end if;

  if nullif(trim(coalesce(new.medicine_name, '')), '') is null then
    raise exception 'Medicine name is required.';
  end if;

  select m.*
  into v_medicine_row
  from public.medicines m
  where lower(trim(m.name)) = lower(trim(new.medicine_name))
    and m.archived_at is null
  order by m.id asc
  limit 1
  for update;

  if v_medicine_row.id is null then
    raise exception 'Medicine "%" does not exist in active inventory.', new.medicine_name;
  end if;

  if coalesce(v_medicine_row.qty, 0) < new.quantity then
    raise exception 'Insufficient stock for "%". Available: %, requested: %.', v_medicine_row.name, coalesce(v_medicine_row.qty, 0), new.quantity;
  end if;

  update public.medicines m
  set qty = m.qty - new.quantity
  where m.id = v_medicine_row.id;

  select ph.doctor_staff_id, c.patient_citizen_id
  into v_doctor_staff_id, v_citizen_id
  from public.prescription_headers ph
  left join public.consultations c on c.id = ph.consultation_id
  where ph.id = new.prescription_id;

  insert into public.medicine_inventory_transactions (
    medicine_id,
    medicine_name,
    change_qty,
    resulting_qty,
    reason,
    prescription_item_id,
    doctor_staff_id,
    created_at
  ) values (
    v_medicine_row.id,
    v_medicine_row.name,
    -new.quantity,
    v_medicine_row.qty - new.quantity,
    'PRESCRIPTION_DISPENSE',
    new.id,
    v_doctor_staff_id,
    v_now
  );

  v_duration_days := greatest(1, least(coalesce(new.duration_days, 1), 30));
  v_times := public.get_frequency_times(new.frequency);

  if v_citizen_id is not null then
    for v_day_offset in 0 .. (v_duration_days - 1) loop
      foreach v_time in array v_times loop
        insert into public.prescription_dosage_schedules (
          prescription_item_id,
          citizen_id,
          medicine_name,
          dosage,
          frequency,
          instructions,
          schedule_date,
          dose_time,
          status
        ) values (
          new.id,
          v_citizen_id,
          new.medicine_name,
          new.dosage,
          new.frequency,
          new.instructions,
          (v_now::date + v_day_offset),
          v_time,
          'pending'
        );
      end loop;
    end loop;
  end if;

  return new;
end;
$$;

drop trigger if exists trg_prescription_items_stock_and_schedule on public.prescription_items;
create trigger trg_prescription_items_stock_and_schedule
after insert on public.prescription_items
for each row execute function public.handle_prescription_item_stock_and_schedule();

create or replace function public.get_my_prescribed_medicines(
  p_limit integer default 10
)
returns table (
  medicine_name text,
  quantity integer,
  unit text,
  dosage text,
  frequency text,
  duration_days integer,
  instructions text,
  doctor_name text,
  issued_at timestamptz
)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_citizen_id bigint;
  v_limit integer := greatest(1, least(coalesce(p_limit, 10), 50));
begin
  select c.id
  into v_citizen_id
  from public.citizens c
  where c.auth_user_id = auth.uid();

  if v_citizen_id is null then
    return;
  end if;

  return query
  select
    pi.medicine_name,
    pi.quantity,
    coalesce(pi.unit, ''),
    coalesce(pi.dosage, ''),
    coalesce(pi.frequency, ''),
    coalesce(pi.duration_days, 1),
    coalesce(pi.instructions, ''),
    coalesce(nullif(trim(concat_ws(' ', s.first_name, s.last_name)), ''), 'Doctor') as doctor_name,
    ph.issued_at
  from public.prescription_items pi
  join public.prescription_headers ph on ph.id = pi.prescription_id
  left join public.consultations c on c.id = ph.consultation_id
  left join public.staff s on s.id = ph.doctor_staff_id
  where c.patient_citizen_id = v_citizen_id
  order by ph.issued_at desc, pi.id desc
  limit v_limit;
end;
$$;

revoke all on function public.get_my_prescribed_medicines(integer) from public;
grant execute on function public.get_my_prescribed_medicines(integer) to authenticated;

create or replace function public.get_my_dosage_schedule(
  p_from date default current_date,
  p_to date default (current_date + 7)
)
returns table (
  id bigint,
  medicine_name text,
  dosage text,
  frequency text,
  instructions text,
  schedule_date date,
  dose_time time,
  status text,
  taken_at timestamptz
)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_citizen_id bigint;
  v_from date := coalesce(p_from, current_date);
  v_to date := coalesce(p_to, current_date + 7);
begin
  if v_to < v_from then
    return;
  end if;

  select c.id
  into v_citizen_id
  from public.citizens c
  where c.auth_user_id = auth.uid();

  if v_citizen_id is null then
    return;
  end if;

  return query
  select
    ds.id,
    ds.medicine_name,
    coalesce(ds.dosage, ''),
    coalesce(ds.frequency, ''),
    coalesce(ds.instructions, ''),
    ds.schedule_date,
    ds.dose_time,
    ds.status,
    ds.taken_at
  from public.prescription_dosage_schedules ds
  where ds.citizen_id = v_citizen_id
    and ds.schedule_date between v_from and v_to
  order by ds.schedule_date asc, ds.dose_time asc;
end;
$$;

revoke all on function public.get_my_dosage_schedule(date, date) from public;
grant execute on function public.get_my_dosage_schedule(date, date) to authenticated;
