-- Enhanced Consultations: vitals, physical examination, chief complaint,
-- lab requests, follow-up scheduling, and consultation status.
-- Also adds patient allergies to citizens for prescription safety.

-- ============================================================
-- 1. Enhance consultations table
-- ============================================================

alter table if exists public.consultations
  add column if not exists chief_complaint text,
  add column if not exists history_of_present_illness text,
  add column if not exists vital_signs jsonb,
  add column if not exists physical_examination jsonb,
  add column if not exists lab_requests jsonb,
  add column if not exists follow_up_date date,
  add column if not exists follow_up_notes text,
  add column if not exists consultation_status text not null default 'completed';

-- Status constraint
alter table public.consultations
  drop constraint if exists consultations_status_valid;
alter table public.consultations
  add constraint consultations_status_valid
  check (consultation_status in ('awaiting', 'in_progress', 'completed'));

-- Index for follow-up queries
create index if not exists idx_consultations_follow_up_date
  on public.consultations(follow_up_date)
  where follow_up_date is not null;

create index if not exists idx_consultations_status
  on public.consultations(consultation_status);

-- ============================================================
-- 2. Add patient allergies to citizens
-- ============================================================

alter table if exists public.citizens
  add column if not exists allergies text[],
  add column if not exists blood_type text,
  add column if not exists medical_notes text;

-- ============================================================
-- 3. Consultation attachments for lab results
-- ============================================================

create table if not exists public.consultation_attachments (
  id bigint generated by default as identity primary key,
  consultation_id bigint not null references public.consultations(id) on delete cascade,
  file_name text not null,
  file_type text,
  file_url text not null,
  description text,
  uploaded_by_staff_id bigint references public.staff(id) on delete set null,
  created_at timestamptz not null default now(),
  constraint consultation_attachments_file_name_non_empty check (length(trim(file_name)) > 0),
  constraint consultation_attachments_file_url_non_empty check (length(trim(file_url)) > 0)
);

create index if not exists idx_consultation_attachments_consultation_id
  on public.consultation_attachments(consultation_id);

alter table public.consultation_attachments enable row level security;

drop policy if exists consultation_attachments_select_active_staff on public.consultation_attachments;
create policy consultation_attachments_select_active_staff
  on public.consultation_attachments
  for select
  using (
    public.is_admin()
    or exists (
      select 1 from public.staff s
      where s.auth_user_id = auth.uid()
        and lower(trim(coalesce(s.status, ''))) = 'active'
    )
  );

drop policy if exists consultation_attachments_insert_active_staff on public.consultation_attachments;
create policy consultation_attachments_insert_active_staff
  on public.consultation_attachments
  for insert
  with check (
    public.is_admin()
    or exists (
      select 1 from public.staff s
      where s.auth_user_id = auth.uid()
        and lower(trim(coalesce(s.status, ''))) = 'active'
        and lower(trim(coalesce(s.role, ''))) in ('doctor', 'nurse')
    )
  );

grant select, insert on public.consultation_attachments to authenticated;

-- ============================================================
-- 4. RPC: Save consultation with vitals (atomic)
-- ============================================================

create or replace function public.save_consultation_with_vitals(
  p_patient_citizen_id bigint,
  p_patient_identifier text,
  p_chief_complaint text,
  p_symptoms text default null,
  p_history_of_present_illness text default null,
  p_vital_signs jsonb default null,
  p_physical_examination jsonb default null,
  p_diagnosis text default '',
  p_notes text default null,
  p_lab_requests jsonb default null,
  p_follow_up_date date default null,
  p_follow_up_notes text default null,
  p_consultation_status text default 'completed'
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_doctor_staff_id bigint;
  v_consultation_id bigint;
  v_status text;
begin
  -- Resolve current doctor
  select s.id into v_doctor_staff_id
  from public.staff s
  where s.auth_user_id = auth.uid()
    and lower(trim(coalesce(s.status, ''))) = 'active'
    and lower(trim(coalesce(s.role, ''))) = 'doctor';

  if v_doctor_staff_id is null then
    return jsonb_build_object('ok', false, 'error', 'Only active doctors can create consultations.');
  end if;

  v_status := coalesce(nullif(trim(p_consultation_status), ''), 'completed');
  if v_status not in ('awaiting', 'in_progress', 'completed') then
    v_status := 'completed';
  end if;

  insert into public.consultations (
    patient_citizen_id,
    patient_identifier,
    doctor_staff_id,
    chief_complaint,
    symptoms,
    history_of_present_illness,
    vital_signs,
    physical_examination,
    diagnosis,
    notes,
    lab_requests,
    follow_up_date,
    follow_up_notes,
    consultation_status
  ) values (
    p_patient_citizen_id,
    coalesce(nullif(trim(p_patient_identifier), ''), 'CIT-' || p_patient_citizen_id),
    v_doctor_staff_id,
    nullif(trim(coalesce(p_chief_complaint, '')), ''),
    nullif(trim(coalesce(p_symptoms, '')), ''),
    nullif(trim(coalesce(p_history_of_present_illness, '')), ''),
    p_vital_signs,
    p_physical_examination,
    coalesce(nullif(trim(p_diagnosis), ''), 'Pending'),
    nullif(trim(coalesce(p_notes, '')), ''),
    p_lab_requests,
    p_follow_up_date,
    nullif(trim(coalesce(p_follow_up_notes, '')), ''),
    v_status
  )
  returning id into v_consultation_id;

  return jsonb_build_object(
    'ok', true,
    'consultation_id', v_consultation_id
  );
end;
$$;

revoke all on function public.save_consultation_with_vitals(
  bigint, text, text, text, text, jsonb, jsonb, text, text, jsonb, date, text, text
) from public;
grant execute on function public.save_consultation_with_vitals(
  bigint, text, text, text, text, jsonb, jsonb, text, text, jsonb, date, text, text
) to authenticated;

-- ============================================================
-- 5. RPC: Get patient consultation history (timeline)
-- ============================================================

create or replace function public.get_patient_consultation_history(
  p_citizen_id bigint
)
returns table (
  id bigint,
  doctor_name text,
  doctor_specialization text,
  chief_complaint text,
  symptoms text,
  diagnosis text,
  notes text,
  vital_signs jsonb,
  physical_examination jsonb,
  lab_requests jsonb,
  follow_up_date date,
  follow_up_notes text,
  consultation_status text,
  consulted_at timestamptz,
  prescription_count bigint
)
language plpgsql
security definer
set search_path = public
as $$
begin
  -- Verify caller is active staff
  if not exists (
    select 1 from public.staff s
    where s.auth_user_id = auth.uid()
      and lower(trim(coalesce(s.status, ''))) = 'active'
  ) and not public.is_admin() then
    return;
  end if;

  return query
  select
    c.id,
    coalesce(nullif(trim(concat_ws(' ', s.first_name, s.last_name)), ''), 'Doctor') as doctor_name,
    coalesce(s.doctor_specialization, '') as doctor_specialization,
    coalesce(c.chief_complaint, '') as chief_complaint,
    coalesce(c.symptoms, '') as symptoms,
    coalesce(c.diagnosis, '') as diagnosis,
    coalesce(c.notes, '') as notes,
    c.vital_signs,
    c.physical_examination,
    c.lab_requests,
    c.follow_up_date,
    coalesce(c.follow_up_notes, '') as follow_up_notes,
    c.consultation_status,
    c.consulted_at,
    (select count(*) from public.prescription_headers ph where ph.consultation_id = c.id) as prescription_count
  from public.consultations c
  left join public.staff s on s.id = c.doctor_staff_id
  where c.patient_citizen_id = p_citizen_id
  order by c.consulted_at desc;
end;
$$;

revoke all on function public.get_patient_consultation_history(bigint) from public;
grant execute on function public.get_patient_consultation_history(bigint) to authenticated;

-- ============================================================
-- 6. RPC: Check prescription safety (allergies + restrictions)
-- ============================================================

create or replace function public.check_prescription_safety(
  p_citizen_id bigint,
  p_medicine_names text[]
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_allergies text[];
  v_warnings jsonb := '[]'::jsonb;
  v_med_name text;
  v_allergy text;
begin
  -- Get patient allergies
  select coalesce(c.allergies, '{}')
  into v_allergies
  from public.citizens c
  where c.id = p_citizen_id;

  -- Check each medicine against allergies
  if array_length(v_allergies, 1) > 0 and array_length(p_medicine_names, 1) > 0 then
    foreach v_med_name in array p_medicine_names loop
      foreach v_allergy in array v_allergies loop
        if lower(trim(v_med_name)) like '%' || lower(trim(v_allergy)) || '%'
           or lower(trim(v_allergy)) like '%' || lower(trim(v_med_name)) || '%' then
          v_warnings := v_warnings || jsonb_build_object(
            'type', 'allergy',
            'severity', 'high',
            'medicine', v_med_name,
            'allergy', v_allergy,
            'message', 'Patient has documented allergy to ' || v_allergy || '. Medicine "' || v_med_name || '" may cause a reaction.'
          );
        end if;
      end loop;
    end loop;
  end if;

  -- Check stock availability
  foreach v_med_name in array p_medicine_names loop
    if not exists (
      select 1 from public.medicines m
      where lower(trim(m.name)) = lower(trim(v_med_name))
        and m.archived_at is null
        and coalesce(m.qty, 0) > 0
    ) then
      v_warnings := v_warnings || jsonb_build_object(
        'type', 'stock',
        'severity', 'medium',
        'medicine', v_med_name,
        'message', 'Medicine "' || v_med_name || '" is out of stock or not in inventory.'
      );
    end if;
  end loop;

  return jsonb_build_object(
    'ok', true,
    'warnings', v_warnings,
    'has_critical', (select count(*) > 0 from jsonb_array_elements(v_warnings) w where w->>'severity' = 'high')
  );
end;
$$;

revoke all on function public.check_prescription_safety(bigint, text[]) from public;
grant execute on function public.check_prescription_safety(bigint, text[]) to authenticated;

-- ============================================================
-- 7. Nurse can record vitals via update on consultation
-- ============================================================

drop policy if exists consultations_update_nurse_vitals on public.consultations;
create policy consultations_update_nurse_vitals
  on public.consultations
  for update
  using (
    exists (
      select 1 from public.staff s
      where s.auth_user_id = auth.uid()
        and lower(trim(coalesce(s.status, ''))) = 'active'
        and lower(trim(coalesce(s.role, ''))) in ('doctor', 'nurse')
    )
  )
  with check (
    exists (
      select 1 from public.staff s
      where s.auth_user_id = auth.uid()
        and lower(trim(coalesce(s.status, ''))) = 'active'
        and lower(trim(coalesce(s.role, ''))) in ('doctor', 'nurse')
    )
  );

grant update on public.consultations to authenticated;
