-- =============================================================================
-- P2-10: Optimize queue_tickets cleanup trigger
--
-- Problem:
--   The BEFORE INSERT ... FOR EACH STATEMENT trigger check_and_delete_old_queue_tickets
--   ran a SELECT EXISTS(...) full-table scan on queue_tickets on EVERY insert.
--
-- Fix:
--   Track the last cleanup date in public.system_config ('last_queue_cleanup_date').
--   Only execute the cleanup DELETE once per day (on the first insert of a new Manila day),
--   avoiding expensive table scans on all subsequent ticket inserts throughout the day.
-- =============================================================================

CREATE TABLE IF NOT EXISTS public.system_config (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  config_key TEXT UNIQUE NOT NULL,
  config_value TEXT NOT NULL,
  description TEXT,
  created_at TIMESTAMPTZ DEFAULT TIMEZONE('Asia/Manila', NOW()),
  updated_at TIMESTAMPTZ DEFAULT TIMEZONE('Asia/Manila', NOW())
);

-- Ensure RLS is active on system_config
ALTER TABLE public.system_config ENABLE ROW LEVEL SECURITY;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies 
    WHERE tablename = 'system_config' AND policyname = 'system_config_read_policy'
  ) THEN
    CREATE POLICY system_config_read_policy
      ON public.system_config FOR SELECT
      USING (true);
  END IF;
END;
$$;

-- Replace trigger function with optimized single-daily execution
CREATE OR REPLACE FUNCTION public.check_and_delete_old_queue_tickets()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_today_manila DATE;
  v_last_cleanup DATE;
BEGIN
  v_today_manila := (NOW() AT TIME ZONE 'Asia/Manila')::date;
  
  -- Fast lookup of last cleanup date
  SELECT config_value::date INTO v_last_cleanup
  FROM public.system_config
  WHERE config_key = 'last_queue_cleanup_date';
  
  -- If already cleaned up today, exit immediately without scanning queue_tickets
  IF v_last_cleanup IS NOT NULL AND v_last_cleanup >= v_today_manila THEN
    RETURN NULL;
  END IF;
  
  -- Perform daily cleanup of tickets created before today in Manila time
  DELETE FROM public.queue_tickets
  WHERE (created_at AT TIME ZONE 'Asia/Manila')::date < v_today_manila;
  
  -- Record that today's cleanup completed
  INSERT INTO public.system_config (config_key, config_value, description, updated_at)
  VALUES ('last_queue_cleanup_date', v_today_manila::text, 'Date of last automated queue ticket cleanup in Manila time', TIMEZONE('Asia/Manila', NOW()))
  ON CONFLICT (config_key) DO UPDATE
    SET config_value = EXCLUDED.config_value,
        updated_at = EXCLUDED.updated_at;
        
  RETURN NULL;
END;
$$;

-- Recreate trigger
DROP TRIGGER IF EXISTS trigger_cleanup_old_queue_tickets ON public.queue_tickets;
CREATE TRIGGER trigger_cleanup_old_queue_tickets
  BEFORE INSERT ON public.queue_tickets
  FOR EACH STATEMENT
  EXECUTE FUNCTION public.check_and_delete_old_queue_tickets();
