-- Migration: 20260902120000_over_the_counter_drugs_system.sql
-- Description: Implement Over-The-Counter (OTC) drug support in inventory and direct dispensing.

-- 1. Add drug_classification column to medicines table
alter table public.medicines
  add column if not exists drug_classification text not null default 'rx'
    check (drug_classification in ('rx', 'otc'));

create index if not exists idx_medicines_classification
  on public.medicines (drug_classification);

-- 2. Mark common known over-the-counter medications as 'otc'
update public.medicines
set drug_classification = 'otc'
where lower(trim(name)) in (
  'paracetamol',
  'ibuprofen',
  'cetirizine',
  'ascorbic acid',
  'vitamin c',
  'multivitamins',
  'oral rehydration salts',
  'ors',
  'antacid',
  'aluminum hydroxide',
  'magnesium hydroxide',
  'loratadine',
  'salbutamol syrup',
  'carbocisteine',
  'mefenamic acid'
)
and drug_classification = 'rx';

-- 3. Create OTC Dispenses Table
create table if not exists public.otc_dispenses (
  id bigint generated by default as identity primary key,
  reference_no text not null unique,
  citizen_id bigint references public.citizens(id) on delete set null,
  walkin_patient_name text not null default 'Walk-in Patient',
  dispensed_by_staff_id bigint not null references public.staff(id),
  dispensed_at timestamptz not null default now(),
  notes text
);

create index if not exists idx_otc_dispenses_ref on public.otc_dispenses (reference_no);
create index if not exists idx_otc_dispenses_date on public.otc_dispenses (dispensed_at desc);
create index if not exists idx_otc_dispenses_citizen on public.otc_dispenses (citizen_id);
create index if not exists idx_otc_dispenses_staff on public.otc_dispenses (dispensed_by_staff_id);

-- 4. Create OTC Dispense Items Table
create table if not exists public.otc_dispense_items (
  id bigint generated by default as identity primary key,
  otc_dispense_id bigint not null references public.otc_dispenses(id) on delete cascade,
  medicine_id bigint not null references public.medicines(id),
  quantity integer not null check (quantity > 0),
  unit text,
  instructions text
);

create index if not exists idx_otc_dispense_items_dispense on public.otc_dispense_items (otc_dispense_id);
create index if not exists idx_otc_dispense_items_med on public.otc_dispense_items (medicine_id);

-- 5. Row Level Security for OTC Dispenses
alter table public.otc_dispenses enable row level security;
alter table public.otc_dispense_items enable row level security;

drop policy if exists otc_dispenses_select_staff on public.otc_dispenses;
create policy otc_dispenses_select_staff
  on public.otc_dispenses
  for select
  using (
    exists (
      select 1 from public.staff s
      where s.auth_user_id = auth.uid()
        and s.status = 'active'
    )
  );

drop policy if exists otc_dispense_items_select_staff on public.otc_dispense_items;
create policy otc_dispense_items_select_staff
  on public.otc_dispense_items
  for select
  using (
    exists (
      select 1 from public.staff s
      where s.auth_user_id = auth.uid()
        and s.status = 'active'
    )
  );

grant select, insert on public.otc_dispenses to authenticated;
grant select, insert on public.otc_dispense_items to authenticated;

-- 6. RPC: Direct OTC Dispensing Function
create or replace function public.dispense_otc_medicines(
  p_citizen_id bigint default null,
  p_patient_name text default null,
  p_items jsonb default '[]'::jsonb,
  p_notes text default null
)
returns json
language plpgsql
security definer
set search_path = public
as $$
declare
  v_staff_id bigint;
  v_role text;
  v_dispense_id bigint;
  v_ref_no text;
  v_date_str text;
  v_random_suffix text;
  v_row record;
  v_med record;
  v_items_count integer := 0;
begin
  -- Authenticate staff role
  select s.id, s.role into v_staff_id, v_role
  from public.staff s
  where s.auth_user_id = auth.uid() and s.status = 'active'
  limit 1;

  if v_staff_id is null then
    return json_build_object('error', 'Not authenticated as active staff.');
  end if;

  if v_role <> 'pharmacist' then
    return json_build_object('error', 'Forbidden: only pharmacists can dispense medicines.');
  end if;

  if p_items is null or jsonb_typeof(p_items) <> 'array' or jsonb_array_length(p_items) = 0 then
    return json_build_object('error', 'No medicines selected for dispensing.');
  end if;

  -- Generate readable reference number: OTC-YYYYMMDD-XXXX
  v_date_str := to_char(timezone('Asia/Manila', now()), 'YYYYMMDD');
  v_random_suffix := lpad(floor(random() * 9000 + 1000)::text, 4, '0');
  v_ref_no := 'OTC-' || v_date_str || '-' || v_random_suffix;

  -- Insert header
  insert into public.otc_dispenses (
    reference_no,
    citizen_id,
    walkin_patient_name,
    dispensed_by_staff_id,
    dispensed_at,
    notes
  ) values (
    v_ref_no,
    p_citizen_id,
    trim(coalesce(nullif(p_patient_name, ''), 'Walk-in Patient')),
    v_staff_id,
    now(),
    p_notes
  ) returning id into v_dispense_id;

  -- Process line items
  for v_row in
    select r.medicine_id, r.quantity, r.instructions
    from jsonb_to_recordset(p_items) as r(medicine_id bigint, quantity integer, instructions text)
  loop
    if v_row.medicine_id is null then
      raise exception 'medicine_id is required for every item.';
    end if;

    if v_row.quantity is null or v_row.quantity <= 0 then
      continue;
    end if;

    -- Lock and verify target medicine
    select m.id, m.name, m.qty, m.unit, m.drug_classification
    into v_med
    from public.medicines m
    where m.id = v_row.medicine_id and m.archived_at is null
    for update;

    if v_med.id is null then
      raise exception 'Medicine ID % not found in inventory.', v_row.medicine_id;
    end if;

    if v_med.drug_classification <> 'otc' then
      raise exception '% is classified as Prescription-Only (Rx) and cannot be dispensed over-the-counter.', v_med.name;
    end if;

    if v_med.qty < v_row.quantity then
      raise exception 'Insufficient stock for % (Available: %, Requested: %).', v_med.name, v_med.qty, v_row.quantity;
    end if;

    -- Deduct stock
    update public.medicines
    set qty = qty - v_row.quantity
    where id = v_med.id;

    -- Record item
    insert into public.otc_dispense_items (
      otc_dispense_id,
      medicine_id,
      quantity,
      unit,
      instructions
    ) values (
      v_dispense_id,
      v_med.id,
      v_row.quantity,
      coalesce(v_med.unit, ''),
      v_row.instructions
    );

    v_items_count := v_items_count + 1;
  end loop;

  if v_items_count = 0 then
    raise exception 'No items with quantity > 0 were dispensed.';
  end if;

  return json_build_object(
    'ok', true,
    'reference_no', v_ref_no,
    'otc_dispense_id', v_dispense_id,
    'items_count', v_items_count
  );
exception when others then
  return json_build_object('error', SQLERRM);
end;
$$;

grant execute on function public.dispense_otc_medicines(bigint, text, jsonb, text) to authenticated;
