-- Reports & Analytics: financial transactions table, patient statistics,
-- inventory reporting, consultation analytics, and audit logging.

-- ============================================================
-- 1. Clinic financial transactions
-- ============================================================

create table if not exists public.clinic_transactions (
  id bigint generated by default as identity primary key,
  transaction_type text not null,
  category text not null,
  amount numeric(12,2) not null,
  description text,
  reference_id text,
  transaction_date date not null default current_date,
  created_by_staff_id bigint references public.staff(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint clinic_transactions_type_valid check (transaction_type in ('income', 'expense')),
  constraint clinic_transactions_amount_positive check (amount >= 0),
  constraint clinic_transactions_category_non_empty check (length(trim(category)) > 0)
);

create index if not exists idx_clinic_transactions_date
  on public.clinic_transactions(transaction_date desc);
create index if not exists idx_clinic_transactions_type_date
  on public.clinic_transactions(transaction_type, transaction_date);

alter table public.clinic_transactions enable row level security;

drop policy if exists clinic_transactions_select_admin on public.clinic_transactions;
create policy clinic_transactions_select_admin
  on public.clinic_transactions
  for select
  using (
    public.is_admin()
    or exists (
      select 1 from public.staff s
      where s.auth_user_id = auth.uid()
        and lower(trim(coalesce(s.status, ''))) = 'active'
    )
  );

drop policy if exists clinic_transactions_insert_admin on public.clinic_transactions;
create policy clinic_transactions_insert_admin
  on public.clinic_transactions
  for insert
  with check (public.is_admin());

drop policy if exists clinic_transactions_update_admin on public.clinic_transactions;
create policy clinic_transactions_update_admin
  on public.clinic_transactions
  for update
  using (public.is_admin());

drop policy if exists clinic_transactions_delete_admin on public.clinic_transactions;
create policy clinic_transactions_delete_admin
  on public.clinic_transactions
  for delete
  using (public.is_admin());

grant select, insert, update, delete on public.clinic_transactions to authenticated;

-- Updated_at trigger
create or replace function public.set_clinic_transactions_updated_at()
returns trigger language plpgsql as $$
begin
  new.updated_at := now();
  return new;
end;
$$;

drop trigger if exists trg_clinic_transactions_updated_at on public.clinic_transactions;
create trigger trg_clinic_transactions_updated_at
  before update on public.clinic_transactions
  for each row execute function public.set_clinic_transactions_updated_at();

-- ============================================================
-- 2. Audit log table
-- ============================================================

create table if not exists public.audit_log (
  id bigint generated by default as identity primary key,
  action text not null,
  entity_type text not null,
  entity_id text,
  details jsonb,
  performed_by_staff_id bigint references public.staff(id) on delete set null,
  performed_by_auth_uid uuid,
  ip_address text,
  created_at timestamptz not null default now()
);

create index if not exists idx_audit_log_created_at on public.audit_log(created_at desc);
create index if not exists idx_audit_log_entity on public.audit_log(entity_type, entity_id);
create index if not exists idx_audit_log_staff on public.audit_log(performed_by_staff_id);

alter table public.audit_log enable row level security;

drop policy if exists audit_log_select_admin on public.audit_log;
create policy audit_log_select_admin
  on public.audit_log
  for select
  using (public.is_admin());

drop policy if exists audit_log_insert_authenticated on public.audit_log;
create policy audit_log_insert_authenticated
  on public.audit_log
  for insert
  with check (true);

grant select, insert on public.audit_log to authenticated;

-- ============================================================
-- 3. RPC: Patient Statistics
-- ============================================================

create or replace function public.get_patient_statistics(
  p_date_from date default (current_date - 30),
  p_date_to date default current_date
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_result jsonb;
  v_total_consultations bigint;
  v_unique_patients bigint;
  v_today_consultations bigint;
  v_gender_dist jsonb;
  v_age_groups jsonb;
  v_top_diagnoses jsonb;
  v_daily_counts jsonb;
begin
  -- Total consultations in range
  select count(*) into v_total_consultations
  from public.consultations c
  where c.consulted_at::date between p_date_from and p_date_to;

  -- Unique patients
  select count(distinct c.patient_citizen_id) into v_unique_patients
  from public.consultations c
  where c.consulted_at::date between p_date_from and p_date_to
    and c.patient_citizen_id is not null;

  -- Today's consultations
  select count(*) into v_today_consultations
  from public.consultations c
  where c.consulted_at::date = current_date;

  -- Gender distribution
  select coalesce(jsonb_agg(row_to_json(g)), '[]'::jsonb)
  into v_gender_dist
  from (
    select coalesce(nullif(trim(cit.sex), ''), 'Unknown') as gender, count(*) as count
    from public.consultations c
    join public.citizens cit on cit.id = c.patient_citizen_id
    where c.consulted_at::date between p_date_from and p_date_to
    group by coalesce(nullif(trim(cit.sex), ''), 'Unknown')
    order by count desc
  ) g;

  -- Age group distribution
  select coalesce(jsonb_agg(row_to_json(a)), '[]'::jsonb)
  into v_age_groups
  from (
    select
      case
        when coalesce(cit.age, 0) <= 5 then '0-5 (Infant)'
        when coalesce(cit.age, 0) <= 12 then '6-12 (Child)'
        when coalesce(cit.age, 0) <= 17 then '13-17 (Adolescent)'
        when coalesce(cit.age, 0) <= 35 then '18-35 (Young Adult)'
        when coalesce(cit.age, 0) <= 59 then '36-59 (Adult)'
        else '60+ (Senior)'
      end as age_group,
      count(*) as count
    from public.consultations c
    join public.citizens cit on cit.id = c.patient_citizen_id
    where c.consulted_at::date between p_date_from and p_date_to
    group by 1
    order by count desc
  ) a;

  -- Top diagnoses
  select coalesce(jsonb_agg(row_to_json(d)), '[]'::jsonb)
  into v_top_diagnoses
  from (
    select coalesce(nullif(trim(c.diagnosis), ''), 'Unspecified') as diagnosis, count(*) as count
    from public.consultations c
    where c.consulted_at::date between p_date_from and p_date_to
      and nullif(trim(c.diagnosis), '') is not null
    group by coalesce(nullif(trim(c.diagnosis), ''), 'Unspecified')
    order by count desc
    limit 10
  ) d;

  -- Daily consultation counts
  select coalesce(jsonb_agg(row_to_json(dc)), '[]'::jsonb)
  into v_daily_counts
  from (
    select c.consulted_at::date as date, count(*) as count
    from public.consultations c
    where c.consulted_at::date between p_date_from and p_date_to
    group by c.consulted_at::date
    order by c.consulted_at::date asc
  ) dc;

  v_result := jsonb_build_object(
    'total_consultations', v_total_consultations,
    'unique_patients', v_unique_patients,
    'today_consultations', v_today_consultations,
    'gender_distribution', v_gender_dist,
    'age_groups', v_age_groups,
    'top_diagnoses', v_top_diagnoses,
    'daily_counts', v_daily_counts,
    'date_from', p_date_from,
    'date_to', p_date_to
  );

  return v_result;
end;
$$;

revoke all on function public.get_patient_statistics(date, date) from public;
grant execute on function public.get_patient_statistics(date, date) to authenticated;

-- ============================================================
-- 4. RPC: Inventory Report
-- ============================================================

create or replace function public.get_inventory_report()
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_result jsonb;
  v_total_medicines bigint;
  v_total_stock bigint;
  v_low_stock_count bigint;
  v_expiring_count bigint;
  v_expired_count bigint;
  v_category_breakdown jsonb;
  v_recent_transactions jsonb;
begin
  select count(*), coalesce(sum(m.qty), 0)
  into v_total_medicines, v_total_stock
  from public.medicines m where m.archived_at is null;

  select count(*) into v_low_stock_count
  from public.medicines m
  where m.archived_at is null and m.qty <= m.reorder_level;

  select count(*) into v_expiring_count
  from public.medicines m
  where m.archived_at is null
    and m.expiration_date is not null
    and m.expiration_date between current_date and (current_date + 90);

  select count(*) into v_expired_count
  from public.medicines m
  where m.archived_at is null
    and m.expiration_date is not null
    and m.expiration_date < current_date;

  select coalesce(jsonb_agg(row_to_json(cb)), '[]'::jsonb)
  into v_category_breakdown
  from (
    select m.category, count(*) as count, coalesce(sum(m.qty), 0) as total_qty
    from public.medicines m where m.archived_at is null
    group by m.category order by count desc
  ) cb;

  select coalesce(jsonb_agg(row_to_json(rt)), '[]'::jsonb)
  into v_recent_transactions
  from (
    select t.medicine_name, t.change_qty, t.resulting_qty, t.reason, t.created_at
    from public.medicine_inventory_transactions t
    order by t.created_at desc
    limit 20
  ) rt;

  return jsonb_build_object(
    'total_medicines', v_total_medicines,
    'total_stock', v_total_stock,
    'low_stock_count', v_low_stock_count,
    'expiring_count', v_expiring_count,
    'expired_count', v_expired_count,
    'category_breakdown', v_category_breakdown,
    'recent_transactions', v_recent_transactions
  );
end;
$$;

revoke all on function public.get_inventory_report() from public;
grant execute on function public.get_inventory_report() to authenticated;

-- ============================================================
-- 5. RPC: Financial Summary
-- ============================================================

create or replace function public.get_financial_summary(
  p_date_from date default (current_date - 30),
  p_date_to date default current_date
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_total_income numeric;
  v_total_expense numeric;
  v_daily_breakdown jsonb;
  v_category_breakdown jsonb;
begin
  select coalesce(sum(case when t.transaction_type = 'income' then t.amount else 0 end), 0),
         coalesce(sum(case when t.transaction_type = 'expense' then t.amount else 0 end), 0)
  into v_total_income, v_total_expense
  from public.clinic_transactions t
  where t.transaction_date between p_date_from and p_date_to;

  select coalesce(jsonb_agg(row_to_json(d)), '[]'::jsonb)
  into v_daily_breakdown
  from (
    select
      t.transaction_date as date,
      coalesce(sum(case when t.transaction_type = 'income' then t.amount else 0 end), 0) as income,
      coalesce(sum(case when t.transaction_type = 'expense' then t.amount else 0 end), 0) as expense
    from public.clinic_transactions t
    where t.transaction_date between p_date_from and p_date_to
    group by t.transaction_date
    order by t.transaction_date asc
  ) d;

  select coalesce(jsonb_agg(row_to_json(c)), '[]'::jsonb)
  into v_category_breakdown
  from (
    select t.category, t.transaction_type,
           coalesce(sum(t.amount), 0) as total
    from public.clinic_transactions t
    where t.transaction_date between p_date_from and p_date_to
    group by t.category, t.transaction_type
    order by total desc
  ) c;

  return jsonb_build_object(
    'total_income', v_total_income,
    'total_expense', v_total_expense,
    'net_income', v_total_income - v_total_expense,
    'daily_breakdown', v_daily_breakdown,
    'category_breakdown', v_category_breakdown,
    'date_from', p_date_from,
    'date_to', p_date_to
  );
end;
$$;

revoke all on function public.get_financial_summary(date, date) from public;
grant execute on function public.get_financial_summary(date, date) to authenticated;

-- ============================================================
-- 6. RPC: Consultation analytics
-- ============================================================

create or replace function public.get_consultation_analytics(
  p_date_from date default (current_date - 30),
  p_date_to date default current_date
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_by_doctor jsonb;
  v_by_status jsonb;
  v_follow_ups_due jsonb;
begin
  select coalesce(jsonb_agg(row_to_json(d)), '[]'::jsonb)
  into v_by_doctor
  from (
    select
      coalesce(nullif(trim(concat_ws(' ', s.first_name, s.last_name)), ''), 'Doctor') as doctor_name,
      coalesce(s.doctor_specialization, '') as specialization,
      count(*) as consultation_count
    from public.consultations c
    left join public.staff s on s.id = c.doctor_staff_id
    where c.consulted_at::date between p_date_from and p_date_to
    group by 1, 2
    order by consultation_count desc
  ) d;

  select coalesce(jsonb_agg(row_to_json(st)), '[]'::jsonb)
  into v_by_status
  from (
    select c.consultation_status as status, count(*) as count
    from public.consultations c
    where c.consulted_at::date between p_date_from and p_date_to
    group by c.consultation_status
  ) st;

  select coalesce(jsonb_agg(row_to_json(f)), '[]'::jsonb)
  into v_follow_ups_due
  from (
    select
      c.id,
      coalesce(c.chief_complaint, c.diagnosis, '') as reason,
      c.follow_up_date,
      coalesce(nullif(trim(concat_ws(' ', cit.firstname, cit.surname)), ''), 'Patient') as patient_name,
      coalesce(nullif(trim(concat_ws(' ', s.first_name, s.last_name)), ''), 'Doctor') as doctor_name
    from public.consultations c
    left join public.citizens cit on cit.id = c.patient_citizen_id
    left join public.staff s on s.id = c.doctor_staff_id
    where c.follow_up_date is not null
      and c.follow_up_date between current_date and (current_date + 14)
    order by c.follow_up_date asc
    limit 20
  ) f;

  return jsonb_build_object(
    'by_doctor', v_by_doctor,
    'by_status', v_by_status,
    'follow_ups_due', v_follow_ups_due
  );
end;
$$;

revoke all on function public.get_consultation_analytics(date, date) from public;
grant execute on function public.get_consultation_analytics(date, date) to authenticated;
