-- Restore Doctor Schedules feature (table + RPCs + policies)

create table if not exists public.doctor_schedules (
  id bigint generated by default as identity primary key,
  doctor_staff_id bigint not null references public.staff(id) on delete cascade,
  doctor_name varchar(200),
  schedule_date date not null,
  start_time time not null,
  end_time time not null,
  notes text,
  created_by_staff_id bigint references public.staff(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint doctor_schedules_time_range_chk check (end_time > start_time)
);

create index if not exists idx_doctor_schedules_date
  on public.doctor_schedules (schedule_date);

create index if not exists idx_doctor_schedules_doctor_date
  on public.doctor_schedules (doctor_staff_id, schedule_date, start_time);

create unique index if not exists uq_doctor_schedules_slot
  on public.doctor_schedules (doctor_staff_id, schedule_date, start_time, end_time);

create or replace function public.set_doctor_schedule_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at := now();
  return new;
end;
$$;

drop trigger if exists trg_doctor_schedules_set_updated_at on public.doctor_schedules;
create trigger trg_doctor_schedules_set_updated_at
before update on public.doctor_schedules
for each row execute function public.set_doctor_schedule_updated_at();

alter table public.doctor_schedules enable row level security;

-- Active staff can read schedules.
drop policy if exists doctor_schedules_select_staff on public.doctor_schedules;
create policy doctor_schedules_select_staff
  on public.doctor_schedules
  for select
  using (
    exists (
      select 1
      from public.staff s
      where s.auth_user_id = auth.uid()
        and lower(s.status) = 'active'
    )
  );

-- Admin-only write operations.
drop policy if exists doctor_schedules_insert_admin on public.doctor_schedules;
create policy doctor_schedules_insert_admin
  on public.doctor_schedules
  for insert
  with check (public.is_admin());

drop policy if exists doctor_schedules_update_admin on public.doctor_schedules;
create policy doctor_schedules_update_admin
  on public.doctor_schedules
  for update
  using (public.is_admin())
  with check (public.is_admin());

drop policy if exists doctor_schedules_delete_admin on public.doctor_schedules;
create policy doctor_schedules_delete_admin
  on public.doctor_schedules
  for delete
  using (public.is_admin());

create or replace function public.purge_expired_doctor_schedules()
returns integer
language plpgsql
security definer
set search_path = public
as $$
declare
  v_deleted integer := 0;
begin
  delete from public.doctor_schedules ds
  where (ds.schedule_date + ds.end_time) < now();

  get diagnostics v_deleted = row_count;
  return coalesce(v_deleted, 0);
end;
$$;

grant execute on function public.purge_expired_doctor_schedules() to authenticated;

create or replace function public.list_doctor_schedules()
returns setof public.doctor_schedules
language plpgsql
security definer
set search_path = public
as $$
declare
  v_role text;
begin
  v_role := lower(coalesce(public.get_staff_role(), ''));
  if v_role = '' then
    raise exception 'Forbidden: active staff account required';
  end if;

  perform public.purge_expired_doctor_schedules();

  return query
  select ds.*
  from public.doctor_schedules ds
  order by ds.schedule_date asc, ds.start_time asc;
end;
$$;

grant execute on function public.list_doctor_schedules() to authenticated;

create or replace function public.list_available_doctor_schedules(
  p_date_from date default current_date,
  p_date_to date default (current_date + interval '30 days')::date
)
returns table (
  id bigint,
  doctor_staff_id bigint,
  doctor_name varchar,
  specialization text,
  schedule_date date,
  start_time time,
  end_time time,
  notes text
)
language plpgsql
security definer
set search_path = public
as $$
begin
  if auth.uid() is null then
    raise exception 'Forbidden: authentication required';
  end if;

  perform public.purge_expired_doctor_schedules();

  return query
  select
    ds.id,
    ds.doctor_staff_id,
    coalesce(
      nullif(trim(ds.doctor_name), ''),
      trim(concat(coalesce(s.first_name, ''), ' ', coalesce(s.last_name, '')))
    )::varchar as doctor_name,
    coalesce(s.doctor_specialization, '')::text as specialization,
    ds.schedule_date,
    ds.start_time,
    ds.end_time,
    ds.notes
  from public.doctor_schedules ds
  join public.staff s
    on s.id = ds.doctor_staff_id
  where lower(trim(coalesce(s.role, ''))) = 'doctor'
    and lower(trim(coalesce(s.status, ''))) = 'active'
    and ds.schedule_date >= p_date_from
    and ds.schedule_date <= p_date_to
  order by ds.schedule_date asc, ds.start_time asc;
end;
$$;

grant execute on function public.list_available_doctor_schedules(date, date) to authenticated;

create or replace function public.upsert_doctor_schedule_admin(
  p_id bigint default null,
  p_doctor_staff_id bigint default null,
  p_schedule_date date default null,
  p_start_time time default null,
  p_end_time time default null,
  p_notes text default null
)
returns public.doctor_schedules
language plpgsql
security definer
set search_path = public
as $$
declare
  v_role text;
  v_actor_staff_id bigint;
  v_user_email text;
  v_schedule public.doctor_schedules;
begin
  v_user_email := lower(coalesce(auth.jwt()->>'email', ''));

  update public.staff
  set auth_user_id = auth.uid()
  where auth.uid() is not null
    and auth_user_id is null
    and lower(email) = v_user_email
    and lower(coalesce(status, '')) = 'active';

  select lower(coalesce(s.role, '')), s.id
    into v_role, v_actor_staff_id
  from public.staff s
  where lower(coalesce(s.status, '')) = 'active'
    and (
      (auth.uid() is not null and s.auth_user_id = auth.uid())
      or (v_user_email <> '' and lower(s.email) = v_user_email)
    )
  order by case when lower(coalesce(s.role, '')) = 'admin' then 0 else 1 end, s.id asc
  limit 1;

  if v_role <> 'admin' then
    raise exception 'Forbidden: admin role required';
  end if;

  perform public.purge_expired_doctor_schedules();

  if p_id is null then
    insert into public.doctor_schedules (
      doctor_staff_id,
      doctor_name,
      schedule_date,
      start_time,
      end_time,
      notes,
      created_by_staff_id
    )
    select
      p_doctor_staff_id,
      trim(concat(coalesce(d.first_name, ''), ' ', coalesce(d.last_name, ''))),
      p_schedule_date,
      p_start_time,
      p_end_time,
      nullif(trim(coalesce(p_notes, '')), ''),
      v_actor_staff_id
    from public.staff d
    where d.id = p_doctor_staff_id
    returning * into v_schedule;
  else
    update public.doctor_schedules ds
    set
      doctor_staff_id = p_doctor_staff_id,
      doctor_name = trim(concat(coalesce(d.first_name, ''), ' ', coalesce(d.last_name, ''))),
      schedule_date = p_schedule_date,
      start_time = p_start_time,
      end_time = p_end_time,
      notes = nullif(trim(coalesce(p_notes, '')), '')
    from public.staff d
    where ds.id = p_id
      and d.id = p_doctor_staff_id
    returning ds.* into v_schedule;
  end if;

  if v_schedule.id is null then
    raise exception 'Failed to save schedule';
  end if;

  return v_schedule;
end;
$$;

grant execute on function public.upsert_doctor_schedule_admin(bigint, bigint, date, time, time, text) to authenticated;

create or replace function public.delete_doctor_schedule_admin(p_id bigint)
returns boolean
language plpgsql
security definer
set search_path = public
as $$
declare
  v_role text;
  v_user_email text;
begin
  v_user_email := lower(coalesce(auth.jwt()->>'email', ''));

  update public.staff
  set auth_user_id = auth.uid()
  where auth.uid() is not null
    and auth_user_id is null
    and lower(email) = v_user_email
    and lower(coalesce(status, '')) = 'active';

  select lower(coalesce(s.role, '')) into v_role
  from public.staff s
  where lower(coalesce(s.status, '')) = 'active'
    and (
      (auth.uid() is not null and s.auth_user_id = auth.uid())
      or (v_user_email <> '' and lower(s.email) = v_user_email)
    )
  order by case when lower(coalesce(s.role, '')) = 'admin' then 0 else 1 end, s.id asc
  limit 1;

  if v_role <> 'admin' then
    raise exception 'Forbidden: admin role required';
  end if;

  delete from public.doctor_schedules where id = p_id;
  return true;
end;
$$;

grant execute on function public.delete_doctor_schedule_admin(bigint) to authenticated;
