-- Create consultations and prescription tables for doctor workflows.

create table if not exists public.consultations (
  id bigint generated by default as identity primary key,
  patient_identifier text not null,
  patient_citizen_id bigint references public.citizens(id) on delete set null,
  doctor_staff_id bigint not null references public.staff(id) on delete restrict,
  symptoms text,
  diagnosis text not null,
  notes text,
  consulted_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint consultations_patient_identifier_non_empty check (length(trim(patient_identifier)) > 0),
  constraint consultations_diagnosis_non_empty check (length(trim(diagnosis)) > 0)
);

create table if not exists public.prescription_headers (
  id bigint generated by default as identity primary key,
  consultation_id bigint references public.consultations(id) on delete set null,
  patient_identifier text not null,
  doctor_staff_id bigint not null references public.staff(id) on delete restrict,
  issued_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint prescription_headers_patient_identifier_non_empty check (length(trim(patient_identifier)) > 0)
);

create table if not exists public.prescription_items (
  id bigint generated by default as identity primary key,
  prescription_id bigint not null references public.prescription_headers(id) on delete cascade,
  medicine_name text not null,
  quantity integer not null,
  unit text,
  created_at timestamptz not null default now(),
  constraint prescription_items_medicine_name_non_empty check (length(trim(medicine_name)) > 0),
  constraint prescription_items_quantity_positive check (quantity > 0)
);

create index if not exists idx_consultations_doctor_staff_id on public.consultations(doctor_staff_id);
create index if not exists idx_consultations_consulted_at on public.consultations(consulted_at desc);
create index if not exists idx_prescription_headers_doctor_staff_id on public.prescription_headers(doctor_staff_id);
create index if not exists idx_prescription_headers_issued_at on public.prescription_headers(issued_at desc);
create index if not exists idx_prescription_items_prescription_id on public.prescription_items(prescription_id);

create or replace function public.set_consultations_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at := now();
  return new;
end;
$$;

drop trigger if exists trg_consultations_set_updated_at on public.consultations;
create trigger trg_consultations_set_updated_at
before update on public.consultations
for each row execute function public.set_consultations_updated_at();

create or replace function public.set_prescription_headers_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at := now();
  return new;
end;
$$;

drop trigger if exists trg_prescription_headers_set_updated_at on public.prescription_headers;
create trigger trg_prescription_headers_set_updated_at
before update on public.prescription_headers
for each row execute function public.set_prescription_headers_updated_at();

alter table public.consultations enable row level security;
alter table public.prescription_headers enable row level security;
alter table public.prescription_items enable row level security;

drop policy if exists consultations_select_active_staff on public.consultations;
create policy consultations_select_active_staff
  on public.consultations
  for select
  using (
    public.is_admin()
    or exists (
      select 1
      from public.staff s
      where s.auth_user_id = auth.uid()
        and lower(trim(coalesce(s.status, ''))) = 'active'
    )
  );

drop policy if exists consultations_insert_doctor_only on public.consultations;
create policy consultations_insert_doctor_only
  on public.consultations
  for insert
  with check (
    exists (
      select 1
      from public.staff s
      where s.id = consultations.doctor_staff_id
        and s.auth_user_id = auth.uid()
        and lower(trim(coalesce(s.status, ''))) = 'active'
        and lower(trim(coalesce(s.role, ''))) = 'doctor'
    )
  );

drop policy if exists prescription_headers_select_active_staff on public.prescription_headers;
create policy prescription_headers_select_active_staff
  on public.prescription_headers
  for select
  using (
    public.is_admin()
    or exists (
      select 1
      from public.staff s
      where s.auth_user_id = auth.uid()
        and lower(trim(coalesce(s.status, ''))) = 'active'
    )
  );

drop policy if exists prescription_headers_insert_doctor_only on public.prescription_headers;
create policy prescription_headers_insert_doctor_only
  on public.prescription_headers
  for insert
  with check (
    exists (
      select 1
      from public.staff s
      where s.id = prescription_headers.doctor_staff_id
        and s.auth_user_id = auth.uid()
        and lower(trim(coalesce(s.status, ''))) = 'active'
        and lower(trim(coalesce(s.role, ''))) = 'doctor'
    )
  );

drop policy if exists prescription_items_select_active_staff on public.prescription_items;
create policy prescription_items_select_active_staff
  on public.prescription_items
  for select
  using (
    public.is_admin()
    or exists (
      select 1
      from public.staff s
      where s.auth_user_id = auth.uid()
        and lower(trim(coalesce(s.status, ''))) = 'active'
    )
  );

drop policy if exists prescription_items_insert_doctor_only on public.prescription_items;
create policy prescription_items_insert_doctor_only
  on public.prescription_items
  for insert
  with check (
    exists (
      select 1
      from public.prescription_headers ph
      join public.staff s on s.id = ph.doctor_staff_id
      where ph.id = prescription_items.prescription_id
        and s.auth_user_id = auth.uid()
        and lower(trim(coalesce(s.status, ''))) = 'active'
        and lower(trim(coalesce(s.role, ''))) = 'doctor'
    )
  );

grant select, insert on public.consultations to authenticated;
grant select, insert on public.prescription_headers to authenticated;
grant select, insert on public.prescription_items to authenticated;
