-- =============================================================================
-- Partial prescription dispensing workflow
--
-- Adds robust item-level quantity tracking to support partial purchases:
-- - prescription status: pending | partial | dispensed | cancelled | expired
-- - per-item dispensed/remaining quantities
-- - immutable dispense event log
-- - new RPC: dispense_prescription_items(code, items, note)
-- - legacy RPC: dispense_prescription(code) now performs full remaining dispense
-- =============================================================================

-- 1) Expand header status model
alter table public.prescription_headers
  add column if not exists first_dispensed_at timestamptz,
  add column if not exists last_dispensed_at timestamptz;

alter table public.prescription_headers
  drop constraint if exists chk_dispensing_status;

alter table public.prescription_headers
  add constraint chk_dispensing_status
  check (dispensing_status in ('pending', 'partial', 'dispensed', 'cancelled', 'expired'));

-- 2) Add item-level quantity tracking
alter table public.prescription_items
  add column if not exists dispensed_quantity integer not null default 0,
  add column if not exists remaining_quantity integer,
  add column if not exists last_dispensed_at timestamptz;

-- Keep existing item-level boolean aligned with quantity accounting.
create or replace function public.sync_prescription_item_quantities()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  new.quantity := coalesce(new.quantity, 0);
  new.dispensed_quantity := coalesce(new.dispensed_quantity, 0);

  if new.quantity <= 0 then
    raise exception 'Prescription item quantity must be greater than 0';
  end if;

  if new.dispensed_quantity < 0 then
    raise exception 'Dispensed quantity cannot be negative';
  end if;

  if new.dispensed_quantity > new.quantity then
    raise exception 'Dispensed quantity (%) cannot exceed prescribed quantity (%)', new.dispensed_quantity, new.quantity;
  end if;

  new.remaining_quantity := new.quantity - new.dispensed_quantity;
  new.is_dispensed := (new.remaining_quantity = 0);

  return new;
end;
$$;

drop trigger if exists trg_sync_prescription_item_quantities on public.prescription_items;
create trigger trg_sync_prescription_item_quantities
before insert or update of quantity, dispensed_quantity
on public.prescription_items
for each row execute function public.sync_prescription_item_quantities();

-- Backfill existing rows.
update public.prescription_items
set
  dispensed_quantity = least(greatest(coalesce(dispensed_quantity, 0), 0), quantity),
  remaining_quantity = quantity - least(greatest(coalesce(dispensed_quantity, 0), 0), quantity),
  is_dispensed = (quantity - least(greatest(coalesce(dispensed_quantity, 0), 0), quantity) = 0)
where true;

alter table public.prescription_items
  drop constraint if exists chk_prescription_items_dispensed_quantity_range;

alter table public.prescription_items
  add constraint chk_prescription_items_dispensed_quantity_range
  check (dispensed_quantity >= 0 and dispensed_quantity <= quantity);

alter table public.prescription_items
  drop constraint if exists chk_prescription_items_remaining_quantity_range;

alter table public.prescription_items
  add constraint chk_prescription_items_remaining_quantity_range
  check (remaining_quantity >= 0 and remaining_quantity <= quantity);

create index if not exists idx_prescription_items_prescription_remaining
  on public.prescription_items (prescription_id, remaining_quantity);

-- 3) Immutable item dispense events (audit/billing basis)
create table if not exists public.prescription_item_dispenses (
  id bigint generated by default as identity primary key,
  prescription_id bigint not null references public.prescription_headers(id) on delete cascade,
  prescription_item_id bigint not null references public.prescription_items(id) on delete cascade,
  medicine_id bigint references public.medicines(id) on delete set null,
  dispensed_quantity integer not null,
  unit text,
  note text,
  dispensed_by_staff_id bigint not null references public.staff(id) on delete restrict,
  dispensed_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  constraint chk_prescription_item_dispenses_qty_positive check (dispensed_quantity > 0)
);

create index if not exists idx_pid_prescription_id on public.prescription_item_dispenses (prescription_id, dispensed_at desc);
create index if not exists idx_pid_prescription_item_id on public.prescription_item_dispenses (prescription_item_id, dispensed_at desc);
create index if not exists idx_pid_dispensed_by_staff_id on public.prescription_item_dispenses (dispensed_by_staff_id, dispensed_at desc);

alter table public.prescription_item_dispenses enable row level security;

drop policy if exists prescription_item_dispenses_select_staff on public.prescription_item_dispenses;
create policy prescription_item_dispenses_select_staff
  on public.prescription_item_dispenses
  for select
  using (
    public.is_admin()
    or exists (
      select 1 from public.staff s
      where s.auth_user_id = auth.uid()
        and s.status = 'active'
        and s.role = 'pharmacist'
    )
  );

drop policy if exists prescription_item_dispenses_insert_pharmacist on public.prescription_item_dispenses;
create policy prescription_item_dispenses_insert_pharmacist
  on public.prescription_item_dispenses
  for insert
  with check (
    exists (
      select 1 from public.staff s
      where s.auth_user_id = auth.uid()
        and s.status = 'active'
        and s.role = 'pharmacist'
        and s.id = prescription_item_dispenses.dispensed_by_staff_id
    )
  );

grant select, insert on public.prescription_item_dispenses to authenticated;

-- 4) Header status recompute helper
create or replace function public.refresh_prescription_header_dispensing_status(p_prescription_id bigint)
returns text
language plpgsql
security definer
set search_path = public
as $$
declare
  v_current_status text;
  v_total_items integer;
  v_fully_dispensed_items integer;
  v_any_dispensed boolean;
  v_new_status text;
  v_now timestamptz := now();
begin
  select ph.dispensing_status
  into v_current_status
  from public.prescription_headers ph
  where ph.id = p_prescription_id
  for update;

  if v_current_status is null then
    raise exception 'Prescription not found (id=%)', p_prescription_id;
  end if;

  if v_current_status in ('cancelled', 'expired') then
    return v_current_status;
  end if;

  select
    count(*)::integer,
    count(*) filter (where coalesce(pi.remaining_quantity, pi.quantity - coalesce(pi.dispensed_quantity, 0), pi.quantity) = 0)::integer,
    bool_or(coalesce(pi.dispensed_quantity, 0) > 0)
  into v_total_items, v_fully_dispensed_items, v_any_dispensed
  from public.prescription_items pi
  where pi.prescription_id = p_prescription_id;

  if coalesce(v_total_items, 0) = 0 then
    v_new_status := 'pending';
  elsif coalesce(v_fully_dispensed_items, 0) = v_total_items then
    v_new_status := 'dispensed';
  elsif coalesce(v_any_dispensed, false) then
    v_new_status := 'partial';
  else
    v_new_status := 'pending';
  end if;

  update public.prescription_headers ph
  set
    dispensing_status = v_new_status,
    first_dispensed_at = case
      when v_new_status in ('partial', 'dispensed') then coalesce(ph.first_dispensed_at, v_now)
      else ph.first_dispensed_at
    end,
    last_dispensed_at = case
      when v_new_status in ('partial', 'dispensed') then v_now
      else ph.last_dispensed_at
    end,
    dispensed_at = case
      when v_new_status = 'dispensed' then coalesce(ph.dispensed_at, v_now)
      else null
    end,
    dispensed_by_staff_id = case
      when v_new_status in ('partial', 'dispensed') and ph.dispensed_by_staff_id is null then (
        select s.id
        from public.staff s
        where s.auth_user_id = auth.uid()
          and s.status = 'active'
        limit 1
      )
      else ph.dispensed_by_staff_id
    end
  where ph.id = p_prescription_id;

  return v_new_status;
end;
$$;

-- 5) Partial dispense RPC (pharmacist only)
create or replace function public.dispense_prescription_items(
  p_prescription_code text,
  p_items jsonb,
  p_note text default null
)
returns json
language plpgsql
security definer
set search_path = public
as $$
declare
  v_staff_id bigint;
  v_role text;
  v_header_id bigint;
  v_header_status text;
  v_row record;
  v_item record;
  v_medicine_id bigint;
  v_medicine_qty integer;
  v_new_status text;
  v_total_rows integer;
begin
  -- Resolve caller.
  select s.id, s.role
  into v_staff_id, v_role
  from public.staff s
  where s.auth_user_id = auth.uid()
    and s.status = 'active'
  limit 1;

  if v_staff_id is null then
    return json_build_object('error', 'Not authenticated as active staff');
  end if;

  if v_role <> 'pharmacist' then
    return json_build_object('error', 'Forbidden: only pharmacists can dispense prescriptions');
  end if;

  if p_items is null or jsonb_typeof(p_items) <> 'array' or jsonb_array_length(p_items) = 0 then
    return json_build_object('error', 'No dispense items provided');
  end if;

  begin
    -- Lock target prescription.
    select ph.id, ph.dispensing_status
    into v_header_id, v_header_status
    from public.prescription_headers ph
    where upper(trim(ph.prescription_code)) = upper(trim(coalesce(p_prescription_code, '')))
    limit 1
    for update;

    if v_header_id is null then
      raise exception 'Prescription not found';
    end if;

    if v_header_status = 'cancelled' then
      raise exception 'Prescription has been cancelled and cannot be dispensed';
    end if;

    if v_header_status = 'expired' then
      raise exception 'Prescription has expired and can no longer be dispensed';
    end if;

    if v_header_status = 'dispensed' then
      raise exception 'Prescription is already fully dispensed';
    end if;

    -- Disallow duplicate item IDs in a single request.
    if exists (
      select 1
      from jsonb_to_recordset(p_items) as r(prescription_item_id bigint, quantity integer)
      group by r.prescription_item_id
      having count(*) > 1
    ) then
      raise exception 'Duplicate prescription_item_id in request payload';
    end if;

    -- Process all requested partials atomically. Any error rolls back all updates.
    for v_row in
      select r.prescription_item_id, r.quantity
      from jsonb_to_recordset(p_items) as r(prescription_item_id bigint, quantity integer)
    loop
      if v_row.prescription_item_id is null then
        raise exception 'prescription_item_id is required for every item';
      end if;

      if v_row.quantity is null or v_row.quantity <= 0 then
        raise exception 'Dispense quantity must be > 0 for item %', v_row.prescription_item_id;
      end if;

      select
        pi.id,
        pi.medicine_name,
        pi.unit,
        pi.quantity,
        coalesce(pi.dispensed_quantity, 0) as dispensed_quantity,
        coalesce(pi.remaining_quantity, pi.quantity - coalesce(pi.dispensed_quantity, 0)) as remaining_quantity
      into v_item
      from public.prescription_items pi
      where pi.id = v_row.prescription_item_id
        and pi.prescription_id = v_header_id
      for update;

      if v_item.id is null then
        raise exception 'Prescription item % not found for this prescription', v_row.prescription_item_id;
      end if;

      if v_row.quantity > v_item.remaining_quantity then
        raise exception
          'Over-dispense blocked for % (remaining: %, requested: %)',
          v_item.medicine_name, v_item.remaining_quantity, v_row.quantity;
      end if;

      select m.id, m.qty
      into v_medicine_id, v_medicine_qty
      from public.medicines m
      where lower(trim(m.name)) = lower(trim(v_item.medicine_name))
        and m.archived_at is null
      order by m.id asc
      limit 1
      for update;

      if v_medicine_id is null then
        raise exception 'Medicine not found in inventory: %', v_item.medicine_name;
      end if;

      if v_medicine_qty < v_row.quantity then
        raise exception
          'Insufficient stock for % (available: %, requested: %)',
          v_item.medicine_name, v_medicine_qty, v_row.quantity;
      end if;

      update public.medicines
      set qty = qty - v_row.quantity
      where id = v_medicine_id;

      update public.prescription_items
      set
        dispensed_quantity = coalesce(dispensed_quantity, 0) + v_row.quantity,
        last_dispensed_at = now()
      where id = v_item.id;

      insert into public.prescription_item_dispenses (
        prescription_id,
        prescription_item_id,
        medicine_id,
        dispensed_quantity,
        unit,
        note,
        dispensed_by_staff_id,
        dispensed_at
      ) values (
        v_header_id,
        v_item.id,
        v_medicine_id,
        v_row.quantity,
        coalesce(v_item.unit, ''),
        p_note,
        v_staff_id,
        now()
      );
    end loop;

    select count(*)::integer
    into v_total_rows
    from jsonb_to_recordset(p_items) as r(prescription_item_id bigint, quantity integer);

    v_new_status := public.refresh_prescription_header_dispensing_status(v_header_id);

    return json_build_object(
      'ok', true,
      'prescription_id', v_header_id,
      'dispensing_status', v_new_status,
      'items_processed', coalesce(v_total_rows, 0)
    );
  exception
    when others then
      return json_build_object('error', SQLERRM);
  end;
end;
$$;

grant execute on function public.dispense_prescription_items(text, jsonb, text) to authenticated;

-- 6) Backward-compatible full dispense wrapper
create or replace function public.dispense_prescription(p_prescription_code text)
returns json
language plpgsql
security definer
set search_path = public
as $$
declare
  v_items jsonb;
begin
  select jsonb_agg(
           jsonb_build_object(
             'prescription_item_id', pi.id,
             'quantity', coalesce(pi.remaining_quantity, pi.quantity - coalesce(pi.dispensed_quantity, 0))
           )
         )
  into v_items
  from public.prescription_items pi
  join public.prescription_headers ph on ph.id = pi.prescription_id
  where upper(trim(ph.prescription_code)) = upper(trim(coalesce(p_prescription_code, '')))
    and coalesce(pi.remaining_quantity, pi.quantity - coalesce(pi.dispensed_quantity, 0)) > 0;

  if v_items is null then
    return json_build_object('error', 'No remaining prescription items to dispense');
  end if;

  return public.dispense_prescription_items(
    p_prescription_code,
    v_items,
    'Full dispense via legacy endpoint'
  );
end;
$$;

grant execute on function public.dispense_prescription(text) to authenticated;

-- 7) Header status backfill from current item balances
with computed as (
  select
    ph.id as prescription_id,
    case
      when ph.dispensing_status in ('cancelled', 'expired') then ph.dispensing_status
      when count(pi.id) = 0 then 'pending'
      when bool_or(coalesce(pi.remaining_quantity, pi.quantity - coalesce(pi.dispensed_quantity, 0)) = 0)
           and bool_and(coalesce(pi.remaining_quantity, pi.quantity - coalesce(pi.dispensed_quantity, 0)) = 0) then 'dispensed'
      when bool_or(coalesce(pi.dispensed_quantity, 0) > 0) then 'partial'
      else 'pending'
    end as new_status
  from public.prescription_headers ph
  left join public.prescription_items pi on pi.prescription_id = ph.id
  group by ph.id, ph.dispensing_status
)
update public.prescription_headers ph
set
  dispensing_status = c.new_status,
  first_dispensed_at = case
    when c.new_status in ('partial', 'dispensed') then coalesce(ph.first_dispensed_at, now())
    else ph.first_dispensed_at
  end,
  last_dispensed_at = case
    when c.new_status in ('partial', 'dispensed') then coalesce(ph.last_dispensed_at, now())
    else ph.last_dispensed_at
  end,
  dispensed_at = case
    when c.new_status = 'dispensed' then coalesce(ph.dispensed_at, now())
    else null
  end
from computed c
where ph.id = c.prescription_id;
