-- ───────────────────────────────────────────────────────────────────────────
-- STANDARDIZE ALL SCHEDULING TO ASIA/MANILA TIMEZONE
-- ───────────────────────────────────────────────────────────────────────────

-- 1. Ensure get_manila_date helper exists (idempotent)
CREATE OR REPLACE FUNCTION public.get_manila_date()
RETURNS date
LANGUAGE sql
STABLE
AS $$
  SELECT (now() AT TIME ZONE 'Asia/Manila')::date;
$$;

-- 2. Helper for current timestamp in Manila
CREATE OR REPLACE FUNCTION public.get_manila_timestamp()
RETURNS timestamptz
LANGUAGE sql
STABLE
AS $$
  SELECT now() AT TIME ZONE 'Asia/Manila';
$$;

-- 3. Fix Doctor Schedule Purge (was using UTC now())
CREATE OR REPLACE FUNCTION public.purge_expired_doctor_schedules()
RETURNS integer
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_deleted integer := 0;
  v_now_manila timestamp;
BEGIN
  -- Get current time in Manila as a simple timestamp for comparison with (date + time)
  v_now_manila := (now() AT TIME ZONE 'Asia/Manila')::timestamp;

  DELETE FROM public.doctor_schedules ds
  WHERE (ds.schedule_date + ds.end_time) < v_now_manila;

  GET DIAGNOSTICS v_deleted = row_count;
  RETURN coalesce(v_deleted, 0);
END;
$$;

-- 4. Update Available Doctor Schedules RPC (fix default date range)
DROP FUNCTION IF EXISTS public.list_available_doctor_schedules(date, date);
CREATE OR REPLACE FUNCTION public.list_available_doctor_schedules(
  p_date_from date DEFAULT public.get_manila_date(),
  p_date_to date DEFAULT (public.get_manila_date() + interval '30 days')::date
)
RETURNS TABLE (
  id bigint,
  doctor_staff_id bigint,
  doctor_name varchar,
  specialization text,
  schedule_date date,
  start_time time,
  end_time time,
  notes text,
  availability_status text
)
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  IF auth.uid() IS NULL THEN
    RAISE EXCEPTION 'Forbidden: authentication required';
  END IF;

  PERFORM public.purge_expired_doctor_schedules();

  RETURN QUERY
  SELECT
    ds.id,
    ds.doctor_staff_id,
    coalesce(
      nullif(trim(ds.doctor_name), ''),
      trim(concat(coalesce(s.first_name, ''), ' ', coalesce(s.last_name, '')))
    )::varchar as doctor_name,
    coalesce(s.doctor_specialization, '')::text as specialization,
    ds.schedule_date,
    ds.start_time,
    ds.end_time,
    ds.notes,
    s.availability_status as availability_status
  FROM public.doctor_schedules ds
  JOIN public.staff s
    ON s.id = ds.doctor_staff_id
  WHERE lower(trim(coalesce(s.role, ''))) = 'doctor'
    AND lower(trim(coalesce(s.status, ''))) = 'active'
    AND ds.schedule_date >= p_date_from
    AND ds.schedule_date <= p_date_to
  ORDER BY ds.schedule_date ASC, ds.start_time ASC;
END;
$$;

-- 5. Create Medicine Intake Logs table (missing from migrations)
CREATE TABLE IF NOT EXISTS public.medicine_intake_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    citizen_id BIGINT REFERENCES public.citizens(id) ON DELETE CASCADE,
    prescription_item_id BIGINT REFERENCES public.prescription_items(id) ON DELETE CASCADE,
    scheduled_time TEXT, -- e.g., "08:00 AM"
    dose_index INTEGER,
    status TEXT DEFAULT 'taken',
    actual_time TIMESTAMPTZ DEFAULT now(),
    created_at TIMESTAMPTZ DEFAULT now()
);

-- Enable RLS for intake logs
ALTER TABLE public.medicine_intake_logs ENABLE ROW LEVEL SECURITY;

-- Policy: Citizens can manage their own logs
DROP POLICY IF EXISTS "Citizens can manage their own intake logs" ON public.medicine_intake_logs;
CREATE POLICY "Citizens can manage their own intake logs"
    ON public.medicine_intake_logs
    FOR ALL
    USING (citizen_id IN (SELECT id FROM public.citizens WHERE auth_user_id = auth.uid()))
    WITH CHECK (citizen_id IN (SELECT id FROM public.citizens WHERE auth_user_id = auth.uid()));

-- Policy: Staff can view logs for clinical review
DROP POLICY IF EXISTS "Staff can view all intake logs" ON public.medicine_intake_logs;
CREATE POLICY "Staff can view all intake logs"
    ON public.medicine_intake_logs
    FOR SELECT
    USING (EXISTS (SELECT 1 FROM public.staff WHERE auth_user_id = auth.uid() AND lower(status) = 'active'));

-- 6. Ensure system config and queue limiter also use Manila date consistently
CREATE OR REPLACE FUNCTION public.get_today_ticket_count()
RETURNS integer
LANGUAGE sql
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT count(*)::integer
  FROM public.queue_tickets
  WHERE queue_date = public.get_manila_date()
    AND lower(trim(coalesce(status, ''))) IN ('serving', 'completed', 'on_call');
$$;

-- 7. Grant permissions
GRANT EXECUTE ON FUNCTION public.get_manila_date() TO authenticated, anon;
GRANT EXECUTE ON FUNCTION public.get_manila_timestamp() TO authenticated, anon;
GRANT EXECUTE ON FUNCTION public.purge_expired_doctor_schedules() TO authenticated;
GRANT EXECUTE ON FUNCTION public.list_available_doctor_schedules(date, date) TO authenticated;
GRANT ALL ON TABLE public.medicine_intake_logs TO authenticated;
GRANT ALL ON TABLE public.medicine_intake_logs TO service_role;
